// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ladulas/store/v1/store.proto

// Package ladulas.store.v1 is the local encrypted store's document format.
//
// Unlike ladulas.v1 this is not a wire format — it never leaves the machine.
// It is protobuf anyway so that the things it holds in common with the wire
// schema, notably TTL grants, are the same generated types on disk as in
// flight.

package storepb

import (
	ladulasv1 "github.com/hugowetterberg/ladulas/pkg/protocol/ladulasv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyOrigin int32

const (
	KeyOrigin_KEY_ORIGIN_UNSPECIFIED KeyOrigin = 0
	// Imported from an existing OpenSSH private key, e.g. a 1Password export.
	KeyOrigin_KEY_ORIGIN_IMPORTED KeyOrigin = 1
	// Generated by Ladulås.
	KeyOrigin_KEY_ORIGIN_GENERATED KeyOrigin = 2
	// Handed over by a paired peer and accepted here (decision S). It is an
	// origin of its own rather than an import because where a key came from is
	// the first thing anybody asks about a key they did not make.
	KeyOrigin_KEY_ORIGIN_RECEIVED KeyOrigin = 3
)

// Enum value maps for KeyOrigin.
var (
	KeyOrigin_name = map[int32]string{
		0: "KEY_ORIGIN_UNSPECIFIED",
		1: "KEY_ORIGIN_IMPORTED",
		2: "KEY_ORIGIN_GENERATED",
		3: "KEY_ORIGIN_RECEIVED",
	}
	KeyOrigin_value = map[string]int32{
		"KEY_ORIGIN_UNSPECIFIED": 0,
		"KEY_ORIGIN_IMPORTED":    1,
		"KEY_ORIGIN_GENERATED":   2,
		"KEY_ORIGIN_RECEIVED":    3,
	}
)

func (x KeyOrigin) Enum() *KeyOrigin {
	p := new(KeyOrigin)
	*p = x
	return p
}

func (x KeyOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_store_v1_store_proto_enumTypes[0].Descriptor()
}

func (KeyOrigin) Type() protoreflect.EnumType {
	return &file_ladulas_store_v1_store_proto_enumTypes[0]
}

func (x KeyOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyOrigin.Descriptor instead.
func (KeyOrigin) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{0}
}

// KeyTransfer records a portable key changing machines (§10, decision S).
//
// The same message serves both directions because they are the same event seen
// from two ends: a peer, its name as it was known at the time, and when. The
// name is kept beside the fingerprint for the reason the trust records keep
// one — a fingerprint is what is authoritative, and a sentence a person reads
// six months later needs the name.
type KeyTransfer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerFingerprint string                 `protobuf:"bytes,1,opt,name=peer_fingerprint,json=peerFingerprint,proto3" json:"peer_fingerprint,omitempty"`
	PeerName        string                 `protobuf:"bytes,2,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	At              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KeyTransfer) Reset() {
	*x = KeyTransfer{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyTransfer) ProtoMessage() {}

func (x *KeyTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyTransfer.ProtoReflect.Descriptor instead.
func (*KeyTransfer) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{0}
}

func (x *KeyTransfer) GetPeerFingerprint() string {
	if x != nil {
		return x.PeerFingerprint
	}
	return ""
}

func (x *KeyTransfer) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *KeyTransfer) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// StoredKey is an SSH key Ladulås holds. The private half is stored in
// unencrypted OpenSSH format — the confidentiality comes from the age
// encryption of the whole document, so that a store backup decrypts to
// something usable with ordinary tooling.
type StoredKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name the user gave the key. Unique within a store.
	Label       string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Fingerprint string `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Algorithm   string `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// The comment from the key file.
	Comment    string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	PublicKey  []byte                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey []byte                 `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	AddedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	Origin     KeyOrigin              `protobuf:"varint,8,opt,name=origin,proto3,enum=ladulas.store.v1.KeyOrigin" json:"origin,omitempty"`
	// A disabled key is still stored but is not offered by the agent.
	Disabled bool `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Set when the private half lives in a platform secure element — an iOS
	// Secure Enclave key, later an Android Keystore one (§10). private_key is
	// then empty and always will be: the point of the arrangement is that these
	// bytes do not exist. The handle is what the platform knows the key by, and
	// the signature is produced behind whatever gate the key was created with,
	// which for an SSH key is a biometric prompt per use.
	HardwareHandle string `protobuf:"bytes,10,opt,name=hardware_handle,json=hardwareHandle,proto3" json:"hardware_handle,omitempty"`
	// Every peer this key has been handed to, and when (decision S). A key with
	// entries here exists somewhere else too, whatever anybody would prefer, and
	// the surfaces say so: a transfer cannot be undone, so the record is the
	// closest thing to an undo there is — it is what tells somebody which far
	// ends have to be rotated when a machine is lost.
	//
	// Never populated for a hardware key: a handle cannot be handed over, and
	// this is the field that says so by being empty forever.
	HandedTo []*KeyTransfer `protobuf:"bytes,11,rep,name=handed_to,json=handedTo,proto3" json:"handed_to,omitempty"`
	// Where the key came from, on a key that arrived from a peer.
	ReceivedFrom *KeyTransfer `protobuf:"bytes,12,opt,name=received_from,json=receivedFrom,proto3" json:"received_from,omitempty"`
	// Whether this key belongs in an agent's identity list — this instance's own
	// agent socket, and the agent of any peer that borrows it (decision T).
	//
	// Separate from disabled, and a weaker thing: a key with this off is offered
	// to nobody and signs whenever something names it, where a disabled key does
	// neither. What it is for is ssh trying every identity it is handed in turn,
	// against a server that allows six attempts.
	//
	// Optional so that unset means yes, which is what every key written before
	// this field existed has to mean.
	AgentUse      *bool `protobuf:"varint,13,opt,name=agent_use,json=agentUse,proto3,oneof" json:"agent_use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredKey) Reset() {
	*x = StoredKey{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredKey) ProtoMessage() {}

func (x *StoredKey) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredKey.ProtoReflect.Descriptor instead.
func (*StoredKey) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{1}
}

func (x *StoredKey) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *StoredKey) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *StoredKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *StoredKey) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *StoredKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *StoredKey) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *StoredKey) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

func (x *StoredKey) GetOrigin() KeyOrigin {
	if x != nil {
		return x.Origin
	}
	return KeyOrigin_KEY_ORIGIN_UNSPECIFIED
}

func (x *StoredKey) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *StoredKey) GetHardwareHandle() string {
	if x != nil {
		return x.HardwareHandle
	}
	return ""
}

func (x *StoredKey) GetHandedTo() []*KeyTransfer {
	if x != nil {
		return x.HandedTo
	}
	return nil
}

func (x *StoredKey) GetReceivedFrom() *KeyTransfer {
	if x != nil {
		return x.ReceivedFrom
	}
	return nil
}

func (x *StoredKey) GetAgentUse() bool {
	if x != nil && x.AgentUse != nil {
		return *x.AgentUse
	}
	return false
}

// PendingKeyOffer is a portable key a paired peer has handed over and nobody
// here has accepted yet (decision S).
//
// It holds key material, and it is in the store for the reason a pending
// pairing is: the two ends of the exchange are rarely awake at once. The side
// that sends is typically a phone, which cannot be dialled back, so an offer
// kept in memory would be lost by an ordinary restart and could only be
// recovered by finding the phone again — and the person who has to answer it is
// at the other machine. Sealed with everything else, capped in number so that a
// paired peer cannot grow this store by sending, and holding nothing that is
// not already about to be held: accepting is what makes it a key.
type PendingKeyOffer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque, minted here, and what an acceptance names. It is not the
	// fingerprint because the answer is about this offer rather than about the
	// key, and the same key may be offered twice.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The peer that sent it, and its name as the trust record had it on arrival.
	PeerFingerprint string `protobuf:"bytes,2,opt,name=peer_fingerprint,json=peerFingerprint,proto3" json:"peer_fingerprint,omitempty"`
	PeerName        string `protobuf:"bytes,3,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	// What the sender called the key. A label is unique within a store, so the
	// receiving side may have to choose another one; this is what it starts from.
	Label       string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Comment     string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Algorithm   string `protobuf:"bytes,6,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Fingerprint string `protobuf:"bytes,7,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	PublicKey   []byte `protobuf:"bytes,8,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The private half in unencrypted OpenSSH format, as a stored key holds one.
	PrivateKey []byte                 `protobuf:"bytes,9,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// What the sending side called this handover, on an offer that was collected
	// rather than pushed. It is what the next collection acknowledges, so that the
	// sender can stop holding the key for a peer that has it.
	HandoverId    string `protobuf:"bytes,11,opt,name=handover_id,json=handoverId,proto3" json:"handover_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingKeyOffer) Reset() {
	*x = PendingKeyOffer{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingKeyOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingKeyOffer) ProtoMessage() {}

func (x *PendingKeyOffer) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingKeyOffer.ProtoReflect.Descriptor instead.
func (*PendingKeyOffer) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{2}
}

func (x *PendingKeyOffer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PendingKeyOffer) GetPeerFingerprint() string {
	if x != nil {
		return x.PeerFingerprint
	}
	return ""
}

func (x *PendingKeyOffer) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *PendingKeyOffer) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PendingKeyOffer) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PendingKeyOffer) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *PendingKeyOffer) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *PendingKeyOffer) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PendingKeyOffer) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *PendingKeyOffer) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *PendingKeyOffer) GetHandoverId() string {
	if x != nil {
		return x.HandoverId
	}
	return ""
}

// QueuedKeyHandover is a portable key this instance has decided to give a peer
// and has not managed to give it yet (decision S).
//
// It exists because half the peers in this design cannot be dialled. A key sent
// to a desktop is handed over in the call that sends it and never lands here for
// longer than that; a key sent to a phone is queued, the phone is woken, and it
// takes the key when it next polls — the same shape as a parked approval, made
// durable because unlike an approval there is nobody blocked on it and no reason
// for it to expire.
//
// The passphrase was re-entered before this was written, which is what makes the
// queue safe to drain without asking again: the deliberate act has happened, and
// what is left is delivery.
type QueuedKeyHandover struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeerFingerprint string                 `protobuf:"bytes,2,opt,name=peer_fingerprint,json=peerFingerprint,proto3" json:"peer_fingerprint,omitempty"`
	PeerName        string                 `protobuf:"bytes,3,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	// The key, as the receiving side needs it. The fingerprint is this instance's
	// own key it refers to, which is what a completed handover is written onto.
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,6,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,7,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	QueuedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuedKeyHandover) Reset() {
	*x = QueuedKeyHandover{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuedKeyHandover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuedKeyHandover) ProtoMessage() {}

func (x *QueuedKeyHandover) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuedKeyHandover.ProtoReflect.Descriptor instead.
func (*QueuedKeyHandover) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{3}
}

func (x *QueuedKeyHandover) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueuedKeyHandover) GetPeerFingerprint() string {
	if x != nil {
		return x.PeerFingerprint
	}
	return ""
}

func (x *QueuedKeyHandover) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *QueuedKeyHandover) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *QueuedKeyHandover) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *QueuedKeyHandover) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *QueuedKeyHandover) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *QueuedKeyHandover) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

// TrustRecord is a paired peer (§7).
//
// The identity public key is the record: the fingerprint is derived from it for
// display, and so is the SPKI hash the TLS channel pins on, so there is one
// authoritative field and nothing that can drift out of agreement with it.
// Everything else is either what the user decided or what the peer told us.
//
// The two direction flags are declared independently by each side and are not
// negotiated. What the peer says it has written down about us is shown on the
// pairing prompt, and then forgotten: our record says what we allow, and
// revoking is unilateral because nothing about it needs the peer's agreement.
type TrustRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint       string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IdentityPublicKey []byte                 `protobuf:"bytes,3,opt,name=identity_public_key,json=identityPublicKey,proto3" json:"identity_public_key,omitempty"`
	// Addresses the peer says it listens on, best first. Only listeners have
	// any; a phone always dials out (§3).
	Addresses []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Whether the peer may approve for us, and whether it may ask us to approve.
	MayApprove bool `protobuf:"varint,5,opt,name=may_approve,json=mayApprove,proto3" json:"may_approve,omitempty"`
	MayRequest bool `protobuf:"varint,6,opt,name=may_request,json=mayRequest,proto3" json:"may_request,omitempty"`
	// Which of our keys the peer may request signatures with (§7, §16). Empty
	// means none: a pairing grants the right to ask and the right to answer, and
	// the right to borrow a key is a third decision, made separately because its
	// blast radius is different from either of the others.
	AllowedKeyFingerprints []string `protobuf:"bytes,7,rep,name=allowed_key_fingerprints,json=allowedKeyFingerprints,proto3" json:"allowed_key_fingerprints,omitempty"`
	// True when the peer may use every key this instance holds, including ones
	// added after the decision was made. The alternative to writing it down is a
	// list that silently fails to cover a key generated tomorrow, which is a
	// worse surprise than a flag somebody set on purpose.
	MayUseAllKeys bool                   `protobuf:"varint,11,opt,name=may_use_all_keys,json=mayUseAllKeys,proto3" json:"may_use_all_keys,omitempty"`
	PairedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=paired_at,json=pairedAt,proto3" json:"paired_at,omitempty"`
	// Corroborating attributes such as a tailnet node name. Never authoritative.
	Attributes map[string]string `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether this instance dialled the peer's pairing code or displayed its own.
	WeInitiated bool `protobuf:"varint,10,opt,name=we_initiated,json=weInitiated,proto3" json:"we_initiated,omitempty"`
	// The pairing session this record came out of. It is kept so that a peer
	// still holding the pending half of a completed pairing can be told, exactly,
	// that this side finished it — rather than being told only that nothing is
	// pending here, which is also what a withdrawal looks like (§7).
	//
	// Empty on records written before pairings became durable, and on nothing
	// else. A session id that matches no pending pairing and no record is a
	// session this instance has no memory of, which is the answer that tells the
	// other side to give up.
	PairingSessionId string `protobuf:"bytes,12,opt,name=pairing_session_id,json=pairingSessionId,proto3" json:"pairing_session_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrustRecord) Reset() {
	*x = TrustRecord{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustRecord) ProtoMessage() {}

func (x *TrustRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustRecord.ProtoReflect.Descriptor instead.
func (*TrustRecord) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{4}
}

func (x *TrustRecord) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *TrustRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrustRecord) GetIdentityPublicKey() []byte {
	if x != nil {
		return x.IdentityPublicKey
	}
	return nil
}

func (x *TrustRecord) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *TrustRecord) GetMayApprove() bool {
	if x != nil {
		return x.MayApprove
	}
	return false
}

func (x *TrustRecord) GetMayRequest() bool {
	if x != nil {
		return x.MayRequest
	}
	return false
}

func (x *TrustRecord) GetAllowedKeyFingerprints() []string {
	if x != nil {
		return x.AllowedKeyFingerprints
	}
	return nil
}

func (x *TrustRecord) GetMayUseAllKeys() bool {
	if x != nil {
		return x.MayUseAllKeys
	}
	return false
}

func (x *TrustRecord) GetPairedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PairedAt
	}
	return nil
}

func (x *TrustRecord) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TrustRecord) GetWeInitiated() bool {
	if x != nil {
		return x.WeInitiated
	}
	return false
}

func (x *TrustRecord) GetPairingSessionId() string {
	if x != nil {
		return x.PairingSessionId
	}
	return ""
}

// PendingPairing is a pairing whose code has been proven and whose two humans
// have not both answered yet (§7).
//
// It is written down on both sides the moment the code is spent, which is what
// makes the rest of a pairing survive everything that used to end it: a phone
// going to sleep, a daemon restarting, a peer that cannot be reached, and a
// person who walks away and comes back tomorrow. Nothing here expires. The
// code's five minutes bought the right to be in this message at all, and a
// human comparing two fingerprints is not something an attacker can guess.
type PendingPairing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session id both sides know the attempt by. Minted by the listening
	// side and returned to the dialling side by PairResponse.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The peer as the exchange established it. The identity key is the record and
	// the fingerprint is derived from it, exactly as in TrustRecord.
	Fingerprint       string `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Name              string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IdentityPublicKey []byte `protobuf:"bytes,4,opt,name=identity_public_key,json=identityPublicKey,proto3" json:"identity_public_key,omitempty"`
	// Where the peer can be reached. Empty for a phone, which never listens —
	// which is why the side that cannot be dialled must be able to drive the
	// reconciliation itself.
	Addresses []string `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// What this side has decided to grant the peer if its user agrees. This is
	// the whole of what completing the pairing will write down.
	//
	// Both sides derive it from one declaration, made by whoever displayed the
	// code (decision AD), so what the peer will write down is the mirror of this
	// and needs no field of its own: a peer that may ask us to approve is a peer
	// we approve for.
	MayApprove bool `protobuf:"varint,6,opt,name=may_approve,json=mayApprove,proto3" json:"may_approve,omitempty"`
	MayRequest bool `protobuf:"varint,7,opt,name=may_request,json=mayRequest,proto3" json:"may_request,omitempty"`
	// Whether this side dialled the code or displayed it.
	WeDialled bool `protobuf:"varint,10,opt,name=we_dialled,json=weDialled,proto3" json:"we_dialled,omitempty"`
	// Whether the peer's identity arrived inside the pairing code, which makes
	// the visual channel the integrity root (§7).
	KeyFromCode bool `protobuf:"varint,11,opt,name=key_from_code,json=keyFromCode,proto3" json:"key_from_code,omitempty"`
	// The address the exchange came from, for the prompt.
	RemoteAddress string `protobuf:"bytes,12,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	// This side's answer, and the peer's as this side last learned it.
	OurAnswer   ladulasv1.PairingAnswer `protobuf:"varint,13,opt,name=our_answer,json=ourAnswer,proto3,enum=ladulas.v1.PairingAnswer" json:"our_answer,omitempty"`
	TheirAnswer ladulasv1.PairingAnswer `protobuf:"varint,14,opt,name=their_answer,json=theirAnswer,proto3,enum=ladulas.v1.PairingAnswer" json:"their_answer,omitempty"`
	StartedAt   *timestamppb.Timestamp  `protobuf:"bytes,15,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	AnsweredAt  *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=answered_at,json=answeredAt,proto3" json:"answered_at,omitempty"`
	// The request id of the confirmation prompt this side raised, so that a
	// surface showing the prompt and a surface showing the pending list are
	// talking about the same thing.
	ConfirmationRequestId string `protobuf:"bytes,17,opt,name=confirmation_request_id,json=confirmationRequestId,proto3" json:"confirmation_request_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PendingPairing) Reset() {
	*x = PendingPairing{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingPairing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingPairing) ProtoMessage() {}

func (x *PendingPairing) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingPairing.ProtoReflect.Descriptor instead.
func (*PendingPairing) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{5}
}

func (x *PendingPairing) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PendingPairing) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *PendingPairing) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PendingPairing) GetIdentityPublicKey() []byte {
	if x != nil {
		return x.IdentityPublicKey
	}
	return nil
}

func (x *PendingPairing) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PendingPairing) GetMayApprove() bool {
	if x != nil {
		return x.MayApprove
	}
	return false
}

func (x *PendingPairing) GetMayRequest() bool {
	if x != nil {
		return x.MayRequest
	}
	return false
}

func (x *PendingPairing) GetWeDialled() bool {
	if x != nil {
		return x.WeDialled
	}
	return false
}

func (x *PendingPairing) GetKeyFromCode() bool {
	if x != nil {
		return x.KeyFromCode
	}
	return false
}

func (x *PendingPairing) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *PendingPairing) GetOurAnswer() ladulasv1.PairingAnswer {
	if x != nil {
		return x.OurAnswer
	}
	return ladulasv1.PairingAnswer(0)
}

func (x *PendingPairing) GetTheirAnswer() ladulasv1.PairingAnswer {
	if x != nil {
		return x.TheirAnswer
	}
	return ladulasv1.PairingAnswer(0)
}

func (x *PendingPairing) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PendingPairing) GetAnsweredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnsweredAt
	}
	return nil
}

func (x *PendingPairing) GetConfirmationRequestId() string {
	if x != nil {
		return x.ConfirmationRequestId
	}
	return ""
}

// BorrowedKey is the public half of a key a paired peer offers this instance
// (§10, decision N).
//
// It is a cache and is written down anyway, for the reason a phone makes
// obvious: what a holder offers used to be learned by asking, so an unreachable
// holder meant the key vanished from every surface that shows keys — and a
// phone is unreachable most of the time by construction. Remembering it makes
// "what can this machine sign with, and where does each of those live" a
// question with an answer at three in the morning.
//
// Only the public half is here, and there is no version of this message that
// could hold more: a KeyRef is a fingerprint, an algorithm, a public key blob,
// a comment and a label. A cached entry can therefore never be used to imply a
// signature — the holder still runs the whole approval decision, and every
// signature still comes back over the channel from the machine that has the
// private half (§8, §16).
type BorrowedKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity fingerprint of the peer that offers it. The trust record is
	// what names it; keeping the fingerprint rather than the name means a rename
	// does not orphan the entry.
	PeerFingerprint string            `protobuf:"bytes,1,opt,name=peer_fingerprint,json=peerFingerprint,proto3" json:"peer_fingerprint,omitempty"`
	Key             *ladulasv1.KeyRef `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// When the holder last confirmed it offers this key. It is what the surfaces
	// show beside a key whose holder is not reachable, because "borrowed from a
	// phone last seen four hours ago" and "borrowed from a phone last seen in
	// March" are different situations.
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowedKey) Reset() {
	*x = BorrowedKey{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowedKey) ProtoMessage() {}

func (x *BorrowedKey) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowedKey.ProtoReflect.Descriptor instead.
func (*BorrowedKey) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{6}
}

func (x *BorrowedKey) GetPeerFingerprint() string {
	if x != nil {
		return x.PeerFingerprint
	}
	return ""
}

func (x *BorrowedKey) GetKey() *ladulasv1.KeyRef {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BorrowedKey) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

// PeerWakeup is what a peer that approves for this instance has announced about
// being woken (§11, §19 open question 2).
//
// It is written down for the same reason a borrowed key is: what the wake-up
// milestone had to survive is the announcing side being asleep. A phone
// announces once, when its token arrives, and is then unreachable for hours —
// so a requester that kept the route in memory would forget how to wake its
// approver every time the daemon restarted, and would go on not knowing until
// the phone was next picked up, which is precisely the moment it was supposed
// to save.
//
// Nothing here is authority for anything. A route says where to knock; whether
// anybody answers, and whether they may, is decided by the peer channel exactly
// as it was before.
type PeerWakeup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerFingerprint string                 `protobuf:"bytes,1,opt,name=peer_fingerprint,json=peerFingerprint,proto3" json:"peer_fingerprint,omitempty"`
	Route           *ladulasv1.WakeupRoute `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	AnnouncedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=announced_at,json=announcedAt,proto3" json:"announced_at,omitempty"`
	// Until when that peer expects to answer this instance without asking
	// anybody, as it last said. What the silent-push carve-out is decided from.
	QuietUntil    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=quiet_until,json=quietUntil,proto3" json:"quiet_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerWakeup) Reset() {
	*x = PeerWakeup{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerWakeup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerWakeup) ProtoMessage() {}

func (x *PeerWakeup) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerWakeup.ProtoReflect.Descriptor instead.
func (*PeerWakeup) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{7}
}

func (x *PeerWakeup) GetPeerFingerprint() string {
	if x != nil {
		return x.PeerFingerprint
	}
	return ""
}

func (x *PeerWakeup) GetRoute() *ladulasv1.WakeupRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *PeerWakeup) GetAnnouncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnnouncedAt
	}
	return nil
}

func (x *PeerWakeup) GetQuietUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.QuietUntil
	}
	return nil
}

// WakeupSettings is this instance's own half: how it has asked to be woken.
//
// Only an instance that cannot be dialled has any use for it, which today means
// a phone. It is opt-in — §11 says every wake-up mode is — and switching it off
// withdraws the route from every peer that holds one.
type WakeupSettings struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The relay to register with. Configuration and never a default compiled in,
	// because self-hosting the relay is a supported path and the whole of what it
	// takes on the client is this string (§11).
	RelayUrl string `protobuf:"bytes,2,opt,name=relay_url,json=relayUrl,proto3" json:"relay_url,omitempty"`
	// The opaque identifier this instance is known by at that relay. Minted here,
	// kept for as long as the relay is unchanged, and handed to peers in an
	// announcement. Changing relays mints a new one: an identifier means nothing
	// at a relay that never issued it.
	InstanceId string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Platform   ladulasv1.PushPlatform `protobuf:"varint,4,opt,name=platform,proto3,enum=ladulas.v1.PushPlatform" json:"platform,omitempty"`
	// The platform's device token as last seen. Kept only so that a token that
	// has not changed is not re-registered on every launch — the platform is the
	// authority and hands it over again every time the app starts.
	DeviceToken   string                 `protobuf:"bytes,5,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeupSettings) Reset() {
	*x = WakeupSettings{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeupSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeupSettings) ProtoMessage() {}

func (x *WakeupSettings) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeupSettings.ProtoReflect.Descriptor instead.
func (*WakeupSettings) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{8}
}

func (x *WakeupSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WakeupSettings) GetRelayUrl() string {
	if x != nil {
		return x.RelayUrl
	}
	return ""
}

func (x *WakeupSettings) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *WakeupSettings) GetPlatform() ladulasv1.PushPlatform {
	if x != nil {
		return x.Platform
	}
	return ladulasv1.PushPlatform(0)
}

func (x *WakeupSettings) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *WakeupSettings) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

// PeerListenSettings is where this instance has been told to listen.
//
// It is the durable half of decision AH: the flag is for the process, this is
// for the machine, and `ladulas listen` writes it. Absent — which is what every
// store written before it says — means the flag or the automatic policy decides,
// and that is not the same as `auto`: a stored `auto` is somebody having said
// "choose for me" and outranks a flag saying nothing.
type PeerListenSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The specification, in the same words the flag takes: `auto`, `off`, or a
	// comma-separated list of addresses. Empty means nobody has said.
	Spec string `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// Whether an address reachable from outside the local network may be bound
	// (decision H). Stored beside the specification because an address that needs
	// it is useless without it, and a person who set one and not the other has a
	// listener that refuses to come up for a reason in another file.
	AllowPublic   bool                   `protobuf:"varint,2,opt,name=allow_public,json=allowPublic,proto3" json:"allow_public,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerListenSettings) Reset() {
	*x = PeerListenSettings{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerListenSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerListenSettings) ProtoMessage() {}

func (x *PeerListenSettings) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerListenSettings.ProtoReflect.Descriptor instead.
func (*PeerListenSettings) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{9}
}

func (x *PeerListenSettings) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *PeerListenSettings) GetAllowPublic() bool {
	if x != nil {
		return x.AllowPublic
	}
	return false
}

func (x *PeerListenSettings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// StoreDocument is the whole decrypted store.
type StoreDocument struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Human assigned name for this instance.
	InstanceName string `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	// The instance identity key in OpenSSH private key format (§7). Empty on an
	// instance whose identity lives in a secure element, which is every phone.
	IdentityKey []byte `protobuf:"bytes,3,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	// Set when the identity is hardware-resident: the handle the platform knows
	// it by, and its public half in SSH wire format so that opening the store
	// does not depend on the secure element being willing to talk (§7, §10).
	//
	// The identity key is deliberately not biometric-gated. It authenticates the
	// channel, and a handshake that asked for a fingerprint would be unusable;
	// the SSH keys are the gated ones.
	IdentityHandle    string                 `protobuf:"bytes,9,opt,name=identity_handle,json=identityHandle,proto3" json:"identity_handle,omitempty"`
	IdentityPublicKey []byte                 `protobuf:"bytes,10,opt,name=identity_public_key,json=identityPublicKey,proto3" json:"identity_public_key,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Keys              []*StoredKey           `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
	// Live TTL grants. Grants are approver-side state (§18), so they belong to
	// the instance that made the promise and survive a restart here.
	Grants []*ladulasv1.Grant `protobuf:"bytes,6,rep,name=grants,proto3" json:"grants,omitempty"`
	Peers  []*TrustRecord     `protobuf:"bytes,7,rep,name=peers,proto3" json:"peers,omitempty"`
	// Pairings that are under way. They live here rather than in memory because
	// an unanswered pairing has to survive a restart on either side, and here
	// rather than beside the store because who is trying to pair with this
	// machine is the same map the trust records are (§7, §10). The cost is
	// stated rather than worked around: a sealed instance can neither list nor
	// answer a pending pairing.
	PendingPairings []*PendingPairing `protobuf:"bytes,11,rep,name=pending_pairings,json=pendingPairings,proto3" json:"pending_pairings,omitempty"`
	// Projects this instance publishes to its approvers (§6). Only the record of
	// what is published lives here — the pages an approver reads are served out
	// of the working directory, and the ones it keeps are kept beside its own
	// store, sealed with the same key.
	Publications []*ladulasv1.Publication `protobuf:"bytes,8,rep,name=publications,proto3" json:"publications,omitempty"`
	// Whether to publish, automatically, any project this instance sends an
	// approval request for (decision Q). Unset means yes: the moment an approver
	// most wants a project's documentation is while it is being asked to sign
	// something in it, and having to remember to publish first is how nobody ever
	// has it. It is optional rather than a plain bool so that "nobody has said"
	// and "somebody said no" are different states, because the default is on.
	AutoPublish *bool `protobuf:"varint,14,opt,name=auto_publish,json=autoPublish,proto3,oneof" json:"auto_publish,omitempty"`
	// How the peers that approve for this instance have asked to be woken (§11),
	// and how this instance has asked to be woken itself. Both are in the store
	// because both are the peer map again: a route says "that machine is a phone
	// reachable at this relay under this identifier", and the identifier is a
	// capability that wakes it.
	PeerWakeups []*PeerWakeup   `protobuf:"bytes,15,rep,name=peer_wakeups,json=peerWakeups,proto3" json:"peer_wakeups,omitempty"`
	Wakeups     *WakeupSettings `protobuf:"bytes,16,opt,name=wakeups,proto3" json:"wakeups,omitempty"`
	// The public halves of the keys paired peers offer this instance, so that
	// they can be listed when the peer that holds them cannot be reached
	// (decision N). Encrypted with everything else, because which machine holds
	// which key is the same map the trust records are.
	BorrowedKeys []*BorrowedKey `protobuf:"bytes,12,rep,name=borrowed_keys,json=borrowedKeys,proto3" json:"borrowed_keys,omitempty"`
	// Delegations paired approvers have handed this instance (decision P): the
	// signed artifact, and what has been done under it and not yet reported.
	//
	// These are the other side of `grants`. A grant here is a promise this
	// instance made and keeps; a delegation is one it was given, and the reason
	// it can answer for itself while the approver is asleep.
	HeldDelegations []*HeldDelegation `protobuf:"bytes,13,rep,name=held_delegations,json=heldDelegations,proto3" json:"held_delegations,omitempty"`
	// Portable keys paired peers have handed over, waiting for somebody here to
	// accept them (decision S). Nothing in this list is usable: it is not offered
	// by the agent, not lent to a peer and not listed as a key, because it is not
	// one until it has been accepted.
	PendingKeyOffers []*PendingKeyOffer `protobuf:"bytes,17,rep,name=pending_key_offers,json=pendingKeyOffers,proto3" json:"pending_key_offers,omitempty"`
	// Portable keys this instance has decided to hand to a peer and has not
	// delivered yet — always empty for longer than a moment only when the peer is
	// a phone, which cannot be dialled and comes to collect instead.
	QueuedKeyHandovers []*QueuedKeyHandover `protobuf:"bytes,18,rep,name=queued_key_handovers,json=queuedKeyHandovers,proto3" json:"queued_key_handovers,omitempty"`
	// Endorsements this instance holds (decision AG), in either of the two roles
	// there are — the requester keeping one to present when it borrows, and a
	// fellow holder of the key keeping one so it can act on it and so it can be
	// seen and taken back. One record covers both because the difference is not a
	// property of the artifact: it is whether this instance holds the key.
	HeldEndorsements []*HeldEndorsement `protobuf:"bytes,19,rep,name=held_endorsements,json=heldEndorsements,proto3" json:"held_endorsements,omitempty"`
	// Where the peer channel has been told to listen, when somebody has said
	// (decision AH). It is in the store rather than beside it because the
	// control socket is the management surface (decision K) and the store is
	// what that surface writes to; a sealed instance does not listen at all, so
	// nothing needs it earlier than the unseal that reads it.
	PeerListen *PeerListenSettings `protobuf:"bytes,21,opt,name=peer_listen,json=peerListen,proto3" json:"peer_listen,omitempty"`
	// Retractions this instance has been told about, kept until what they take
	// back would have expired anyway (decision AG).
	//
	// They are kept whether or not there is an endorsement here to apply them to.
	// A retraction can arrive before the endorsement it kills — it gossips and
	// the endorsement is carried by the requester — and one that was discarded
	// for naming nothing would let the endorsement land afterwards and be
	// honoured.
	Retractions   []*HeldRetraction `protobuf:"bytes,20,rep,name=retractions,proto3" json:"retractions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDocument) Reset() {
	*x = StoreDocument{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDocument) ProtoMessage() {}

func (x *StoreDocument) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDocument.ProtoReflect.Descriptor instead.
func (*StoreDocument) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{10}
}

func (x *StoreDocument) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StoreDocument) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *StoreDocument) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *StoreDocument) GetIdentityHandle() string {
	if x != nil {
		return x.IdentityHandle
	}
	return ""
}

func (x *StoreDocument) GetIdentityPublicKey() []byte {
	if x != nil {
		return x.IdentityPublicKey
	}
	return nil
}

func (x *StoreDocument) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StoreDocument) GetKeys() []*StoredKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *StoreDocument) GetGrants() []*ladulasv1.Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *StoreDocument) GetPeers() []*TrustRecord {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *StoreDocument) GetPendingPairings() []*PendingPairing {
	if x != nil {
		return x.PendingPairings
	}
	return nil
}

func (x *StoreDocument) GetPublications() []*ladulasv1.Publication {
	if x != nil {
		return x.Publications
	}
	return nil
}

func (x *StoreDocument) GetAutoPublish() bool {
	if x != nil && x.AutoPublish != nil {
		return *x.AutoPublish
	}
	return false
}

func (x *StoreDocument) GetPeerWakeups() []*PeerWakeup {
	if x != nil {
		return x.PeerWakeups
	}
	return nil
}

func (x *StoreDocument) GetWakeups() *WakeupSettings {
	if x != nil {
		return x.Wakeups
	}
	return nil
}

func (x *StoreDocument) GetBorrowedKeys() []*BorrowedKey {
	if x != nil {
		return x.BorrowedKeys
	}
	return nil
}

func (x *StoreDocument) GetHeldDelegations() []*HeldDelegation {
	if x != nil {
		return x.HeldDelegations
	}
	return nil
}

func (x *StoreDocument) GetPendingKeyOffers() []*PendingKeyOffer {
	if x != nil {
		return x.PendingKeyOffers
	}
	return nil
}

func (x *StoreDocument) GetQueuedKeyHandovers() []*QueuedKeyHandover {
	if x != nil {
		return x.QueuedKeyHandovers
	}
	return nil
}

func (x *StoreDocument) GetHeldEndorsements() []*HeldEndorsement {
	if x != nil {
		return x.HeldEndorsements
	}
	return nil
}

func (x *StoreDocument) GetPeerListen() *PeerListenSettings {
	if x != nil {
		return x.PeerListen
	}
	return nil
}

func (x *StoreDocument) GetRetractions() []*HeldRetraction {
	if x != nil {
		return x.Retractions
	}
	return nil
}

// HeldEndorsement is an endorsement this instance keeps, and its ledger
// (decision AG).
type HeldEndorsement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed artifact exactly as it arrived, kept whole because the
	// signatures cover these bytes and re-marshalling could produce others.
	Signed *ladulasv1.SignedEndorsement `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	// The endorsement it covers, unmarshalled once both signatures verified, so
	// that matching a request against one is not a signature check per request.
	Endorsement *ladulasv1.Endorsement `protobuf:"bytes,2,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
	ReceivedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// How it got here: carried by the requester with a borrowed-signing request,
	// or published by a peer ahead of any request. Worth keeping because they
	// answer different questions — a published one was known before it could be
	// spent, and a presented one was not.
	Published bool `protobuf:"varint,4,opt,name=published,proto3" json:"published,omitempty"`
	// What this instance has signed under it and not yet reported to the issuer,
	// and the total, which is the number worth showing. The same account a
	// delegation keeps, and for the same reason: the issuer promised this and is
	// owed a record of what its promise did.
	UnreportedUses []*ladulasv1.GrantUse `protobuf:"bytes,5,rep,name=unreported_uses,json=unreportedUses,proto3" json:"unreported_uses,omitempty"`
	UseCount       uint32                `protobuf:"varint,6,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeldEndorsement) Reset() {
	*x = HeldEndorsement{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeldEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeldEndorsement) ProtoMessage() {}

func (x *HeldEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeldEndorsement.ProtoReflect.Descriptor instead.
func (*HeldEndorsement) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{11}
}

func (x *HeldEndorsement) GetSigned() *ladulasv1.SignedEndorsement {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *HeldEndorsement) GetEndorsement() *ladulasv1.Endorsement {
	if x != nil {
		return x.Endorsement
	}
	return nil
}

func (x *HeldEndorsement) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *HeldEndorsement) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *HeldEndorsement) GetUnreportedUses() []*ladulasv1.GrantUse {
	if x != nil {
		return x.UnreportedUses
	}
	return nil
}

func (x *HeldEndorsement) GetUseCount() uint32 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

// HeldRetraction is a retraction this instance remembers.
type HeldRetraction struct {
	state      protoimpl.MessageState      `protogen:"open.v1"`
	Signed     *ladulasv1.SignedRetraction `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	Retraction *ladulasv1.Retraction       `protobuf:"bytes,2,opt,name=retraction,proto3" json:"retraction,omitempty"`
	ReceivedAt *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// The peers this instance has passed it on to, so that gossip converges
	// instead of bouncing a retraction between two machines for as long as it
	// is remembered.
	GossipedTo    []string `protobuf:"bytes,4,rep,name=gossiped_to,json=gossipedTo,proto3" json:"gossiped_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeldRetraction) Reset() {
	*x = HeldRetraction{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeldRetraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeldRetraction) ProtoMessage() {}

func (x *HeldRetraction) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeldRetraction.ProtoReflect.Descriptor instead.
func (*HeldRetraction) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{12}
}

func (x *HeldRetraction) GetSigned() *ladulasv1.SignedRetraction {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *HeldRetraction) GetRetraction() *ladulasv1.Retraction {
	if x != nil {
		return x.Retraction
	}
	return nil
}

func (x *HeldRetraction) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *HeldRetraction) GetGossipedTo() []string {
	if x != nil {
		return x.GossipedTo
	}
	return nil
}

// HeldDelegation is a delegation this instance was given, and its ledger.
type HeldDelegation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed artifact exactly as it arrived. Kept whole rather than taken
	// apart, because the signature covers these bytes and re-marshalling could
	// produce different ones.
	Signed *ladulasv1.SignedDelegation `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	// The delegation the artifact covers, unmarshalled once the signature
	// verified, so that matching a request against it does not mean verifying a
	// signature on every request.
	Delegation *ladulasv1.Delegation `protobuf:"bytes,2,opt,name=delegation,proto3" json:"delegation,omitempty"`
	// When it arrived.
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// What has been self-approved under it and not yet acknowledged by the
	// approver. Kept until it is, so that a machine that has been offline for a
	// week still has an account to give when it comes back.
	UnreportedUses []*ladulasv1.GrantUse `protobuf:"bytes,4,rep,name=unreported_uses,json=unreportedUses,proto3" json:"unreported_uses,omitempty"`
	// How many times it has been used in total, which is the number worth
	// showing and does not shrink when a report is acknowledged.
	UseCount      uint32 `protobuf:"varint,5,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeldDelegation) Reset() {
	*x = HeldDelegation{}
	mi := &file_ladulas_store_v1_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeldDelegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeldDelegation) ProtoMessage() {}

func (x *HeldDelegation) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_store_v1_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeldDelegation.ProtoReflect.Descriptor instead.
func (*HeldDelegation) Descriptor() ([]byte, []int) {
	return file_ladulas_store_v1_store_proto_rawDescGZIP(), []int{13}
}

func (x *HeldDelegation) GetSigned() *ladulasv1.SignedDelegation {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *HeldDelegation) GetDelegation() *ladulasv1.Delegation {
	if x != nil {
		return x.Delegation
	}
	return nil
}

func (x *HeldDelegation) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *HeldDelegation) GetUnreportedUses() []*ladulasv1.GrantUse {
	if x != nil {
		return x.UnreportedUses
	}
	return nil
}

func (x *HeldDelegation) GetUseCount() uint32 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

var File_ladulas_store_v1_store_proto protoreflect.FileDescriptor

const file_ladulas_store_v1_store_proto_rawDesc = "" +
	"\n" +
	"\x1cladulas/store/v1/store.proto\x12\x10ladulas.store.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19ladulas/v1/approval.proto\x1a\x18ladulas/v1/project.proto\x1a\x18ladulas/v1/service.proto\x1a\x17ladulas/v1/wakeup.proto\"\x81\x01\n" +
	"\vKeyTransfer\x12)\n" +
	"\x10peer_fingerprint\x18\x01 \x01(\tR\x0fpeerFingerprint\x12\x1b\n" +
	"\tpeer_name\x18\x02 \x01(\tR\bpeerName\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\x9c\x04\n" +
	"\tStoredKey\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x06 \x01(\fR\n" +
	"privateKey\x125\n" +
	"\badded_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\x123\n" +
	"\x06origin\x18\b \x01(\x0e2\x1b.ladulas.store.v1.KeyOriginR\x06origin\x12\x1a\n" +
	"\bdisabled\x18\t \x01(\bR\bdisabled\x12'\n" +
	"\x0fhardware_handle\x18\n" +
	" \x01(\tR\x0ehardwareHandle\x12:\n" +
	"\thanded_to\x18\v \x03(\v2\x1d.ladulas.store.v1.KeyTransferR\bhandedTo\x12B\n" +
	"\rreceived_from\x18\f \x01(\v2\x1d.ladulas.store.v1.KeyTransferR\freceivedFrom\x12 \n" +
	"\tagent_use\x18\r \x01(\bH\x00R\bagentUse\x88\x01\x01B\f\n" +
	"\n" +
	"_agent_use\"\xf7\x02\n" +
	"\x0fPendingKeyOffer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10peer_fingerprint\x18\x02 \x01(\tR\x0fpeerFingerprint\x12\x1b\n" +
	"\tpeer_name\x18\x03 \x01(\tR\bpeerName\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1c\n" +
	"\talgorithm\x18\x06 \x01(\tR\talgorithm\x12 \n" +
	"\vfingerprint\x18\a \x01(\tR\vfingerprint\x12\x1d\n" +
	"\n" +
	"public_key\x18\b \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\t \x01(\fR\n" +
	"privateKey\x12;\n" +
	"\vreceived_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12\x1f\n" +
	"\vhandover_id\x18\v \x01(\tR\n" +
	"handoverId\"\x97\x02\n" +
	"\x11QueuedKeyHandover\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10peer_fingerprint\x18\x02 \x01(\tR\x0fpeerFingerprint\x12\x1b\n" +
	"\tpeer_name\x18\x03 \x01(\tR\bpeerName\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12 \n" +
	"\vfingerprint\x18\x06 \x01(\tR\vfingerprint\x12\x1f\n" +
	"\vprivate_key\x18\a \x01(\fR\n" +
	"privateKey\x127\n" +
	"\tqueued_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\"\xce\x04\n" +
	"\vTrustRecord\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13identity_public_key\x18\x03 \x01(\fR\x11identityPublicKey\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\x1f\n" +
	"\vmay_approve\x18\x05 \x01(\bR\n" +
	"mayApprove\x12\x1f\n" +
	"\vmay_request\x18\x06 \x01(\bR\n" +
	"mayRequest\x128\n" +
	"\x18allowed_key_fingerprints\x18\a \x03(\tR\x16allowedKeyFingerprints\x12'\n" +
	"\x10may_use_all_keys\x18\v \x01(\bR\rmayUseAllKeys\x127\n" +
	"\tpaired_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bpairedAt\x12M\n" +
	"\n" +
	"attributes\x18\t \x03(\v2-.ladulas.store.v1.TrustRecord.AttributesEntryR\n" +
	"attributes\x12!\n" +
	"\fwe_initiated\x18\n" +
	" \x01(\bR\vweInitiated\x12,\n" +
	"\x12pairing_session_id\x18\f \x01(\tR\x10pairingSessionId\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x05\n" +
	"\x0ePendingPairing\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x13identity_public_key\x18\x04 \x01(\fR\x11identityPublicKey\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses\x12\x1f\n" +
	"\vmay_approve\x18\x06 \x01(\bR\n" +
	"mayApprove\x12\x1f\n" +
	"\vmay_request\x18\a \x01(\bR\n" +
	"mayRequest\x12\x1d\n" +
	"\n" +
	"we_dialled\x18\n" +
	" \x01(\bR\tweDialled\x12\"\n" +
	"\rkey_from_code\x18\v \x01(\bR\vkeyFromCode\x12%\n" +
	"\x0eremote_address\x18\f \x01(\tR\rremoteAddress\x128\n" +
	"\n" +
	"our_answer\x18\r \x01(\x0e2\x19.ladulas.v1.PairingAnswerR\tourAnswer\x12<\n" +
	"\ftheir_answer\x18\x0e \x01(\x0e2\x19.ladulas.v1.PairingAnswerR\vtheirAnswer\x129\n" +
	"\n" +
	"started_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vanswered_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"answeredAt\x126\n" +
	"\x17confirmation_request_id\x18\x11 \x01(\tR\x15confirmationRequestIdJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"R\x10peer_may_approveR\x10peer_may_request\"\x9c\x01\n" +
	"\vBorrowedKey\x12)\n" +
	"\x10peer_fingerprint\x18\x01 \x01(\tR\x0fpeerFingerprint\x12$\n" +
	"\x03key\x18\x02 \x01(\v2\x12.ladulas.v1.KeyRefR\x03key\x12<\n" +
	"\flast_seen_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\xe2\x01\n" +
	"\n" +
	"PeerWakeup\x12)\n" +
	"\x10peer_fingerprint\x18\x01 \x01(\tR\x0fpeerFingerprint\x12-\n" +
	"\x05route\x18\x02 \x01(\v2\x17.ladulas.v1.WakeupRouteR\x05route\x12=\n" +
	"\fannounced_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vannouncedAt\x12;\n" +
	"\vquiet_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"quietUntil\"\x82\x02\n" +
	"\x0eWakeupSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\trelay_url\x18\x02 \x01(\tR\brelayUrl\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\bplatform\x18\x04 \x01(\x0e2\x18.ladulas.v1.PushPlatformR\bplatform\x12!\n" +
	"\fdevice_token\x18\x05 \x01(\tR\vdeviceToken\x12?\n" +
	"\rregistered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"\x86\x01\n" +
	"\x12PeerListenSettings\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\tR\x04spec\x12!\n" +
	"\fallow_public\x18\x02 \x01(\bR\vallowPublic\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xea\t\n" +
	"\rStoreDocument\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12!\n" +
	"\fidentity_key\x18\x03 \x01(\fR\videntityKey\x12'\n" +
	"\x0fidentity_handle\x18\t \x01(\tR\x0eidentityHandle\x12.\n" +
	"\x13identity_public_key\x18\n" +
	" \x01(\fR\x11identityPublicKey\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12/\n" +
	"\x04keys\x18\x05 \x03(\v2\x1b.ladulas.store.v1.StoredKeyR\x04keys\x12)\n" +
	"\x06grants\x18\x06 \x03(\v2\x11.ladulas.v1.GrantR\x06grants\x123\n" +
	"\x05peers\x18\a \x03(\v2\x1d.ladulas.store.v1.TrustRecordR\x05peers\x12K\n" +
	"\x10pending_pairings\x18\v \x03(\v2 .ladulas.store.v1.PendingPairingR\x0fpendingPairings\x12;\n" +
	"\fpublications\x18\b \x03(\v2\x17.ladulas.v1.PublicationR\fpublications\x12&\n" +
	"\fauto_publish\x18\x0e \x01(\bH\x00R\vautoPublish\x88\x01\x01\x12?\n" +
	"\fpeer_wakeups\x18\x0f \x03(\v2\x1c.ladulas.store.v1.PeerWakeupR\vpeerWakeups\x12:\n" +
	"\awakeups\x18\x10 \x01(\v2 .ladulas.store.v1.WakeupSettingsR\awakeups\x12B\n" +
	"\rborrowed_keys\x18\f \x03(\v2\x1d.ladulas.store.v1.BorrowedKeyR\fborrowedKeys\x12K\n" +
	"\x10held_delegations\x18\r \x03(\v2 .ladulas.store.v1.HeldDelegationR\x0fheldDelegations\x12O\n" +
	"\x12pending_key_offers\x18\x11 \x03(\v2!.ladulas.store.v1.PendingKeyOfferR\x10pendingKeyOffers\x12U\n" +
	"\x14queued_key_handovers\x18\x12 \x03(\v2#.ladulas.store.v1.QueuedKeyHandoverR\x12queuedKeyHandovers\x12N\n" +
	"\x11held_endorsements\x18\x13 \x03(\v2!.ladulas.store.v1.HeldEndorsementR\x10heldEndorsements\x12E\n" +
	"\vpeer_listen\x18\x15 \x01(\v2$.ladulas.store.v1.PeerListenSettingsR\n" +
	"peerListen\x12B\n" +
	"\vretractions\x18\x14 \x03(\v2 .ladulas.store.v1.HeldRetractionR\vretractionsB\x0f\n" +
	"\r_auto_publish\"\xba\x02\n" +
	"\x0fHeldEndorsement\x125\n" +
	"\x06signed\x18\x01 \x01(\v2\x1d.ladulas.v1.SignedEndorsementR\x06signed\x129\n" +
	"\vendorsement\x18\x02 \x01(\v2\x17.ladulas.v1.EndorsementR\vendorsement\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12\x1c\n" +
	"\tpublished\x18\x04 \x01(\bR\tpublished\x12=\n" +
	"\x0funreported_uses\x18\x05 \x03(\v2\x14.ladulas.v1.GrantUseR\x0eunreportedUses\x12\x1b\n" +
	"\tuse_count\x18\x06 \x01(\rR\buseCount\"\xdc\x01\n" +
	"\x0eHeldRetraction\x124\n" +
	"\x06signed\x18\x01 \x01(\v2\x1c.ladulas.v1.SignedRetractionR\x06signed\x126\n" +
	"\n" +
	"retraction\x18\x02 \x01(\v2\x16.ladulas.v1.RetractionR\n" +
	"retraction\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12\x1f\n" +
	"\vgossiped_to\x18\x04 \x03(\tR\n" +
	"gossipedTo\"\x97\x02\n" +
	"\x0eHeldDelegation\x124\n" +
	"\x06signed\x18\x01 \x01(\v2\x1c.ladulas.v1.SignedDelegationR\x06signed\x126\n" +
	"\n" +
	"delegation\x18\x02 \x01(\v2\x16.ladulas.v1.DelegationR\n" +
	"delegation\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12=\n" +
	"\x0funreported_uses\x18\x04 \x03(\v2\x14.ladulas.v1.GrantUseR\x0eunreportedUses\x12\x1b\n" +
	"\tuse_count\x18\x05 \x01(\rR\buseCount*s\n" +
	"\tKeyOrigin\x12\x1a\n" +
	"\x16KEY_ORIGIN_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13KEY_ORIGIN_IMPORTED\x10\x01\x12\x18\n" +
	"\x14KEY_ORIGIN_GENERATED\x10\x02\x12\x17\n" +
	"\x13KEY_ORIGIN_RECEIVED\x10\x03B7Z5github.com/hugowetterberg/ladulas/pkg/storepb;storepbb\x06proto3"

var (
	file_ladulas_store_v1_store_proto_rawDescOnce sync.Once
	file_ladulas_store_v1_store_proto_rawDescData []byte
)

func file_ladulas_store_v1_store_proto_rawDescGZIP() []byte {
	file_ladulas_store_v1_store_proto_rawDescOnce.Do(func() {
		file_ladulas_store_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ladulas_store_v1_store_proto_rawDesc), len(file_ladulas_store_v1_store_proto_rawDesc)))
	})
	return file_ladulas_store_v1_store_proto_rawDescData
}

var file_ladulas_store_v1_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ladulas_store_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ladulas_store_v1_store_proto_goTypes = []any{
	(KeyOrigin)(0),                      // 0: ladulas.store.v1.KeyOrigin
	(*KeyTransfer)(nil),                 // 1: ladulas.store.v1.KeyTransfer
	(*StoredKey)(nil),                   // 2: ladulas.store.v1.StoredKey
	(*PendingKeyOffer)(nil),             // 3: ladulas.store.v1.PendingKeyOffer
	(*QueuedKeyHandover)(nil),           // 4: ladulas.store.v1.QueuedKeyHandover
	(*TrustRecord)(nil),                 // 5: ladulas.store.v1.TrustRecord
	(*PendingPairing)(nil),              // 6: ladulas.store.v1.PendingPairing
	(*BorrowedKey)(nil),                 // 7: ladulas.store.v1.BorrowedKey
	(*PeerWakeup)(nil),                  // 8: ladulas.store.v1.PeerWakeup
	(*WakeupSettings)(nil),              // 9: ladulas.store.v1.WakeupSettings
	(*PeerListenSettings)(nil),          // 10: ladulas.store.v1.PeerListenSettings
	(*StoreDocument)(nil),               // 11: ladulas.store.v1.StoreDocument
	(*HeldEndorsement)(nil),             // 12: ladulas.store.v1.HeldEndorsement
	(*HeldRetraction)(nil),              // 13: ladulas.store.v1.HeldRetraction
	(*HeldDelegation)(nil),              // 14: ladulas.store.v1.HeldDelegation
	nil,                                 // 15: ladulas.store.v1.TrustRecord.AttributesEntry
	(*timestamppb.Timestamp)(nil),       // 16: google.protobuf.Timestamp
	(ladulasv1.PairingAnswer)(0),        // 17: ladulas.v1.PairingAnswer
	(*ladulasv1.KeyRef)(nil),            // 18: ladulas.v1.KeyRef
	(*ladulasv1.WakeupRoute)(nil),       // 19: ladulas.v1.WakeupRoute
	(ladulasv1.PushPlatform)(0),         // 20: ladulas.v1.PushPlatform
	(*ladulasv1.Grant)(nil),             // 21: ladulas.v1.Grant
	(*ladulasv1.Publication)(nil),       // 22: ladulas.v1.Publication
	(*ladulasv1.SignedEndorsement)(nil), // 23: ladulas.v1.SignedEndorsement
	(*ladulasv1.Endorsement)(nil),       // 24: ladulas.v1.Endorsement
	(*ladulasv1.GrantUse)(nil),          // 25: ladulas.v1.GrantUse
	(*ladulasv1.SignedRetraction)(nil),  // 26: ladulas.v1.SignedRetraction
	(*ladulasv1.Retraction)(nil),        // 27: ladulas.v1.Retraction
	(*ladulasv1.SignedDelegation)(nil),  // 28: ladulas.v1.SignedDelegation
	(*ladulasv1.Delegation)(nil),        // 29: ladulas.v1.Delegation
}
var file_ladulas_store_v1_store_proto_depIdxs = []int32{
	16, // 0: ladulas.store.v1.KeyTransfer.at:type_name -> google.protobuf.Timestamp
	16, // 1: ladulas.store.v1.StoredKey.added_at:type_name -> google.protobuf.Timestamp
	0,  // 2: ladulas.store.v1.StoredKey.origin:type_name -> ladulas.store.v1.KeyOrigin
	1,  // 3: ladulas.store.v1.StoredKey.handed_to:type_name -> ladulas.store.v1.KeyTransfer
	1,  // 4: ladulas.store.v1.StoredKey.received_from:type_name -> ladulas.store.v1.KeyTransfer
	16, // 5: ladulas.store.v1.PendingKeyOffer.received_at:type_name -> google.protobuf.Timestamp
	16, // 6: ladulas.store.v1.QueuedKeyHandover.queued_at:type_name -> google.protobuf.Timestamp
	16, // 7: ladulas.store.v1.TrustRecord.paired_at:type_name -> google.protobuf.Timestamp
	15, // 8: ladulas.store.v1.TrustRecord.attributes:type_name -> ladulas.store.v1.TrustRecord.AttributesEntry
	17, // 9: ladulas.store.v1.PendingPairing.our_answer:type_name -> ladulas.v1.PairingAnswer
	17, // 10: ladulas.store.v1.PendingPairing.their_answer:type_name -> ladulas.v1.PairingAnswer
	16, // 11: ladulas.store.v1.PendingPairing.started_at:type_name -> google.protobuf.Timestamp
	16, // 12: ladulas.store.v1.PendingPairing.answered_at:type_name -> google.protobuf.Timestamp
	18, // 13: ladulas.store.v1.BorrowedKey.key:type_name -> ladulas.v1.KeyRef
	16, // 14: ladulas.store.v1.BorrowedKey.last_seen_at:type_name -> google.protobuf.Timestamp
	19, // 15: ladulas.store.v1.PeerWakeup.route:type_name -> ladulas.v1.WakeupRoute
	16, // 16: ladulas.store.v1.PeerWakeup.announced_at:type_name -> google.protobuf.Timestamp
	16, // 17: ladulas.store.v1.PeerWakeup.quiet_until:type_name -> google.protobuf.Timestamp
	20, // 18: ladulas.store.v1.WakeupSettings.platform:type_name -> ladulas.v1.PushPlatform
	16, // 19: ladulas.store.v1.WakeupSettings.registered_at:type_name -> google.protobuf.Timestamp
	16, // 20: ladulas.store.v1.PeerListenSettings.updated_at:type_name -> google.protobuf.Timestamp
	16, // 21: ladulas.store.v1.StoreDocument.created_at:type_name -> google.protobuf.Timestamp
	2,  // 22: ladulas.store.v1.StoreDocument.keys:type_name -> ladulas.store.v1.StoredKey
	21, // 23: ladulas.store.v1.StoreDocument.grants:type_name -> ladulas.v1.Grant
	5,  // 24: ladulas.store.v1.StoreDocument.peers:type_name -> ladulas.store.v1.TrustRecord
	6,  // 25: ladulas.store.v1.StoreDocument.pending_pairings:type_name -> ladulas.store.v1.PendingPairing
	22, // 26: ladulas.store.v1.StoreDocument.publications:type_name -> ladulas.v1.Publication
	8,  // 27: ladulas.store.v1.StoreDocument.peer_wakeups:type_name -> ladulas.store.v1.PeerWakeup
	9,  // 28: ladulas.store.v1.StoreDocument.wakeups:type_name -> ladulas.store.v1.WakeupSettings
	7,  // 29: ladulas.store.v1.StoreDocument.borrowed_keys:type_name -> ladulas.store.v1.BorrowedKey
	14, // 30: ladulas.store.v1.StoreDocument.held_delegations:type_name -> ladulas.store.v1.HeldDelegation
	3,  // 31: ladulas.store.v1.StoreDocument.pending_key_offers:type_name -> ladulas.store.v1.PendingKeyOffer
	4,  // 32: ladulas.store.v1.StoreDocument.queued_key_handovers:type_name -> ladulas.store.v1.QueuedKeyHandover
	12, // 33: ladulas.store.v1.StoreDocument.held_endorsements:type_name -> ladulas.store.v1.HeldEndorsement
	10, // 34: ladulas.store.v1.StoreDocument.peer_listen:type_name -> ladulas.store.v1.PeerListenSettings
	13, // 35: ladulas.store.v1.StoreDocument.retractions:type_name -> ladulas.store.v1.HeldRetraction
	23, // 36: ladulas.store.v1.HeldEndorsement.signed:type_name -> ladulas.v1.SignedEndorsement
	24, // 37: ladulas.store.v1.HeldEndorsement.endorsement:type_name -> ladulas.v1.Endorsement
	16, // 38: ladulas.store.v1.HeldEndorsement.received_at:type_name -> google.protobuf.Timestamp
	25, // 39: ladulas.store.v1.HeldEndorsement.unreported_uses:type_name -> ladulas.v1.GrantUse
	26, // 40: ladulas.store.v1.HeldRetraction.signed:type_name -> ladulas.v1.SignedRetraction
	27, // 41: ladulas.store.v1.HeldRetraction.retraction:type_name -> ladulas.v1.Retraction
	16, // 42: ladulas.store.v1.HeldRetraction.received_at:type_name -> google.protobuf.Timestamp
	28, // 43: ladulas.store.v1.HeldDelegation.signed:type_name -> ladulas.v1.SignedDelegation
	29, // 44: ladulas.store.v1.HeldDelegation.delegation:type_name -> ladulas.v1.Delegation
	16, // 45: ladulas.store.v1.HeldDelegation.received_at:type_name -> google.protobuf.Timestamp
	25, // 46: ladulas.store.v1.HeldDelegation.unreported_uses:type_name -> ladulas.v1.GrantUse
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_ladulas_store_v1_store_proto_init() }
func file_ladulas_store_v1_store_proto_init() {
	if File_ladulas_store_v1_store_proto != nil {
		return
	}
	file_ladulas_store_v1_store_proto_msgTypes[1].OneofWrappers = []any{}
	file_ladulas_store_v1_store_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ladulas_store_v1_store_proto_rawDesc), len(file_ladulas_store_v1_store_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ladulas_store_v1_store_proto_goTypes,
		DependencyIndexes: file_ladulas_store_v1_store_proto_depIdxs,
		EnumInfos:         file_ladulas_store_v1_store_proto_enumTypes,
		MessageInfos:      file_ladulas_store_v1_store_proto_msgTypes,
	}.Build()
	File_ladulas_store_v1_store_proto = out.File
	file_ladulas_store_v1_store_proto_goTypes = nil
	file_ladulas_store_v1_store_proto_depIdxs = nil
}
