// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ladulas/v1/service.proto

package ladulasv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	ladulasv1 "github.com/hugowetterberg/ladulas/pkg/protocol/ladulasv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApprovalServiceName is the fully-qualified name of the ApprovalService service.
	ApprovalServiceName = "ladulas.v1.ApprovalService"
	// InboxServiceName is the fully-qualified name of the InboxService service.
	InboxServiceName = "ladulas.v1.InboxService"
	// KeyServiceName is the fully-qualified name of the KeyService service.
	KeyServiceName = "ladulas.v1.KeyService"
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "ladulas.v1.ProjectService"
	// PairingServiceName is the fully-qualified name of the PairingService service.
	PairingServiceName = "ladulas.v1.PairingService"
	// PresenceServiceName is the fully-qualified name of the PresenceService service.
	PresenceServiceName = "ladulas.v1.PresenceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApprovalServiceRequestApprovalProcedure is the fully-qualified name of the ApprovalService's
	// RequestApproval RPC.
	ApprovalServiceRequestApprovalProcedure = "/ladulas.v1.ApprovalService/RequestApproval"
	// ApprovalServiceCancelApprovalProcedure is the fully-qualified name of the ApprovalService's
	// CancelApproval RPC.
	ApprovalServiceCancelApprovalProcedure = "/ladulas.v1.ApprovalService/CancelApproval"
	// ApprovalServiceFetchDiffProcedure is the fully-qualified name of the ApprovalService's FetchDiff
	// RPC.
	ApprovalServiceFetchDiffProcedure = "/ladulas.v1.ApprovalService/FetchDiff"
	// InboxServiceFetchPendingProcedure is the fully-qualified name of the InboxService's FetchPending
	// RPC.
	InboxServiceFetchPendingProcedure = "/ladulas.v1.InboxService/FetchPending"
	// InboxServiceAnswerPendingProcedure is the fully-qualified name of the InboxService's
	// AnswerPending RPC.
	InboxServiceAnswerPendingProcedure = "/ladulas.v1.InboxService/AnswerPending"
	// InboxServiceReportGrantUseProcedure is the fully-qualified name of the InboxService's
	// ReportGrantUse RPC.
	InboxServiceReportGrantUseProcedure = "/ladulas.v1.InboxService/ReportGrantUse"
	// InboxServiceReconcileGrantsProcedure is the fully-qualified name of the InboxService's
	// ReconcileGrants RPC.
	InboxServiceReconcileGrantsProcedure = "/ladulas.v1.InboxService/ReconcileGrants"
	// KeyServiceListKeysProcedure is the fully-qualified name of the KeyService's ListKeys RPC.
	KeyServiceListKeysProcedure = "/ladulas.v1.KeyService/ListKeys"
	// KeyServiceRemoteSignProcedure is the fully-qualified name of the KeyService's RemoteSign RPC.
	KeyServiceRemoteSignProcedure = "/ladulas.v1.KeyService/RemoteSign"
	// KeyServiceOfferKeyProcedure is the fully-qualified name of the KeyService's OfferKey RPC.
	KeyServiceOfferKeyProcedure = "/ladulas.v1.KeyService/OfferKey"
	// KeyServiceCollectKeyOffersProcedure is the fully-qualified name of the KeyService's
	// CollectKeyOffers RPC.
	KeyServiceCollectKeyOffersProcedure = "/ladulas.v1.KeyService/CollectKeyOffers"
	// KeyServiceAnnounceKeysProcedure is the fully-qualified name of the KeyService's AnnounceKeys RPC.
	KeyServiceAnnounceKeysProcedure = "/ladulas.v1.KeyService/AnnounceKeys"
	// ProjectServiceListProjectsProcedure is the fully-qualified name of the ProjectService's
	// ListProjects RPC.
	ProjectServiceListProjectsProcedure = "/ladulas.v1.ProjectService/ListProjects"
	// ProjectServiceListDirectoryProcedure is the fully-qualified name of the ProjectService's
	// ListDirectory RPC.
	ProjectServiceListDirectoryProcedure = "/ladulas.v1.ProjectService/ListDirectory"
	// ProjectServiceSearchProjectFilesProcedure is the fully-qualified name of the ProjectService's
	// SearchProjectFiles RPC.
	ProjectServiceSearchProjectFilesProcedure = "/ladulas.v1.ProjectService/SearchProjectFiles"
	// ProjectServiceFetchProjectFileProcedure is the fully-qualified name of the ProjectService's
	// FetchProjectFile RPC.
	ProjectServiceFetchProjectFileProcedure = "/ladulas.v1.ProjectService/FetchProjectFile"
	// PairingServicePairProcedure is the fully-qualified name of the PairingService's Pair RPC.
	PairingServicePairProcedure = "/ladulas.v1.PairingService/Pair"
	// PairingServiceSettlePairingProcedure is the fully-qualified name of the PairingService's
	// SettlePairing RPC.
	PairingServiceSettlePairingProcedure = "/ladulas.v1.PairingService/SettlePairing"
	// PresenceServicePingProcedure is the fully-qualified name of the PresenceService's Ping RPC.
	PresenceServicePingProcedure = "/ladulas.v1.PresenceService/Ping"
	// PresenceServiceWatchProcedure is the fully-qualified name of the PresenceService's Watch RPC.
	PresenceServiceWatchProcedure = "/ladulas.v1.PresenceService/Watch"
)

// ApprovalServiceClient is a client for the ladulas.v1.ApprovalService service.
type ApprovalServiceClient interface {
	// RequestApproval submits a request and streams back its lifecycle. The
	// stream is how first-response-wins cancellation reaches the approver: the
	// requester cancels it and the approver drops the prompt.
	RequestApproval(context.Context, *connect.Request[ladulasv1.RequestApprovalRequest]) (*connect.ServerStreamForClient[ladulasv1.ApprovalEvent], error)
	// CancelApproval withdraws a request out of band, for approvers that answered
	// on a different connection.
	CancelApproval(context.Context, *connect.Request[ladulasv1.CancelApprovalRequest]) (*connect.Response[ladulasv1.CancelApprovalResponse], error)
	// FetchDiff asks the requester for the diff it could not fit in the request.
	//
	// A signing request carries the diff capped (§5), because it travels to a
	// phone and an unbounded diff is both a denial of service and a good place to
	// hide a change. The cap is a display decision rather than a limit on what an
	// approver may see, so an approver that wants the rest asks for it — and asks
	// the requester, over a connection the requester has already agreed to, about
	// a request the requester is at that moment waiting on.
	FetchDiff(context.Context, *connect.Request[ladulasv1.FetchDiffRequest]) (*connect.Response[ladulasv1.FetchDiffResponse], error)
}

// NewApprovalServiceClient constructs a client for the ladulas.v1.ApprovalService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApprovalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApprovalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	approvalServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("ApprovalService").Methods()
	return &approvalServiceClient{
		requestApproval: connect.NewClient[ladulasv1.RequestApprovalRequest, ladulasv1.ApprovalEvent](
			httpClient,
			baseURL+ApprovalServiceRequestApprovalProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("RequestApproval")),
			connect.WithClientOptions(opts...),
		),
		cancelApproval: connect.NewClient[ladulasv1.CancelApprovalRequest, ladulasv1.CancelApprovalResponse](
			httpClient,
			baseURL+ApprovalServiceCancelApprovalProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("CancelApproval")),
			connect.WithClientOptions(opts...),
		),
		fetchDiff: connect.NewClient[ladulasv1.FetchDiffRequest, ladulasv1.FetchDiffResponse](
			httpClient,
			baseURL+ApprovalServiceFetchDiffProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("FetchDiff")),
			connect.WithClientOptions(opts...),
		),
	}
}

// approvalServiceClient implements ApprovalServiceClient.
type approvalServiceClient struct {
	requestApproval *connect.Client[ladulasv1.RequestApprovalRequest, ladulasv1.ApprovalEvent]
	cancelApproval  *connect.Client[ladulasv1.CancelApprovalRequest, ladulasv1.CancelApprovalResponse]
	fetchDiff       *connect.Client[ladulasv1.FetchDiffRequest, ladulasv1.FetchDiffResponse]
}

// RequestApproval calls ladulas.v1.ApprovalService.RequestApproval.
func (c *approvalServiceClient) RequestApproval(ctx context.Context, req *connect.Request[ladulasv1.RequestApprovalRequest]) (*connect.ServerStreamForClient[ladulasv1.ApprovalEvent], error) {
	return c.requestApproval.CallServerStream(ctx, req)
}

// CancelApproval calls ladulas.v1.ApprovalService.CancelApproval.
func (c *approvalServiceClient) CancelApproval(ctx context.Context, req *connect.Request[ladulasv1.CancelApprovalRequest]) (*connect.Response[ladulasv1.CancelApprovalResponse], error) {
	return c.cancelApproval.CallUnary(ctx, req)
}

// FetchDiff calls ladulas.v1.ApprovalService.FetchDiff.
func (c *approvalServiceClient) FetchDiff(ctx context.Context, req *connect.Request[ladulasv1.FetchDiffRequest]) (*connect.Response[ladulasv1.FetchDiffResponse], error) {
	return c.fetchDiff.CallUnary(ctx, req)
}

// ApprovalServiceHandler is an implementation of the ladulas.v1.ApprovalService service.
type ApprovalServiceHandler interface {
	// RequestApproval submits a request and streams back its lifecycle. The
	// stream is how first-response-wins cancellation reaches the approver: the
	// requester cancels it and the approver drops the prompt.
	RequestApproval(context.Context, *connect.Request[ladulasv1.RequestApprovalRequest], *connect.ServerStream[ladulasv1.ApprovalEvent]) error
	// CancelApproval withdraws a request out of band, for approvers that answered
	// on a different connection.
	CancelApproval(context.Context, *connect.Request[ladulasv1.CancelApprovalRequest]) (*connect.Response[ladulasv1.CancelApprovalResponse], error)
	// FetchDiff asks the requester for the diff it could not fit in the request.
	//
	// A signing request carries the diff capped (§5), because it travels to a
	// phone and an unbounded diff is both a denial of service and a good place to
	// hide a change. The cap is a display decision rather than a limit on what an
	// approver may see, so an approver that wants the rest asks for it — and asks
	// the requester, over a connection the requester has already agreed to, about
	// a request the requester is at that moment waiting on.
	FetchDiff(context.Context, *connect.Request[ladulasv1.FetchDiffRequest]) (*connect.Response[ladulasv1.FetchDiffResponse], error)
}

// NewApprovalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApprovalServiceHandler(svc ApprovalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	approvalServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("ApprovalService").Methods()
	approvalServiceRequestApprovalHandler := connect.NewServerStreamHandler(
		ApprovalServiceRequestApprovalProcedure,
		svc.RequestApproval,
		connect.WithSchema(approvalServiceMethods.ByName("RequestApproval")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceCancelApprovalHandler := connect.NewUnaryHandler(
		ApprovalServiceCancelApprovalProcedure,
		svc.CancelApproval,
		connect.WithSchema(approvalServiceMethods.ByName("CancelApproval")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceFetchDiffHandler := connect.NewUnaryHandler(
		ApprovalServiceFetchDiffProcedure,
		svc.FetchDiff,
		connect.WithSchema(approvalServiceMethods.ByName("FetchDiff")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ladulas.v1.ApprovalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApprovalServiceRequestApprovalProcedure:
			approvalServiceRequestApprovalHandler.ServeHTTP(w, r)
		case ApprovalServiceCancelApprovalProcedure:
			approvalServiceCancelApprovalHandler.ServeHTTP(w, r)
		case ApprovalServiceFetchDiffProcedure:
			approvalServiceFetchDiffHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApprovalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApprovalServiceHandler struct{}

func (UnimplementedApprovalServiceHandler) RequestApproval(context.Context, *connect.Request[ladulasv1.RequestApprovalRequest], *connect.ServerStream[ladulasv1.ApprovalEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.ApprovalService.RequestApproval is not implemented"))
}

func (UnimplementedApprovalServiceHandler) CancelApproval(context.Context, *connect.Request[ladulasv1.CancelApprovalRequest]) (*connect.Response[ladulasv1.CancelApprovalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.ApprovalService.CancelApproval is not implemented"))
}

func (UnimplementedApprovalServiceHandler) FetchDiff(context.Context, *connect.Request[ladulasv1.FetchDiffRequest]) (*connect.Response[ladulasv1.FetchDiffResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.ApprovalService.FetchDiff is not implemented"))
}

// InboxServiceClient is a client for the ladulas.v1.InboxService service.
type InboxServiceClient interface {
	// FetchPending returns the requests this instance is currently waiting on the
	// caller to answer.
	//
	// Wait makes it a long poll. Without one an approval would take as long as
	// the phone's next poll, and with one a phone with the app open is as
	// immediate as a desktop that was dialled — the "live connection" of §11 with
	// the connection pointing the other way.
	FetchPending(context.Context, *connect.Request[ladulasv1.FetchPendingRequest]) (*connect.Response[ladulasv1.FetchPendingResponse], error)
	// AnswerPending settles one of them.
	AnswerPending(context.Context, *connect.Request[ladulasv1.AnswerPendingRequest]) (*connect.Response[ladulasv1.AnswerPendingResponse], error)
	// ReportGrantUse is the requester pushing what it has done, over the link it
	// already holds (decision P).
	//
	// It is served by the approver and called by the requester, which is the
	// opposite of everything else here — and it is the direction that works
	// between two desktops, where the requester dials and the approver listens.
	// An approver that cannot be dialled never receives one; it is told there is
	// something waiting by the flag on a poll's answer, and comes to collect it
	// with ReconcileGrants.
	//
	// Nothing is lost when it fails. The uses stay in the requester's ledger
	// until they are acknowledged, so the push is an optimisation on the pull and
	// never the only way an account gets told.
	ReportGrantUse(context.Context, *connect.Request[ladulasv1.ReportGrantUseRequest]) (*connect.Response[ladulasv1.ReportGrantUseResponse], error)
	// ReconcileGrants brings a delegated grant's two halves back into line
	// (decision P). The approver drives it, in both directions at once: it says
	// which delegations it has taken back, and is told what has been done under
	// the ones it has not.
	//
	// The approver drives because it is the side that can always dial. A phone
	// advertises no address and collects rather than listens, so a requester that
	// had to report in would have nowhere to report to — the same asymmetry the
	// inbox above exists for.
	//
	// Nothing here is load-bearing for a delegation working. One that cannot be
	// reconciled goes on being honoured until it expires, which is the whole
	// point of having handed it over; revocation is best-effort and bounded by
	// the expiry the approver chose when it granted it.
	ReconcileGrants(context.Context, *connect.Request[ladulasv1.ReconcileGrantsRequest]) (*connect.Response[ladulasv1.ReconcileGrantsResponse], error)
}

// NewInboxServiceClient constructs a client for the ladulas.v1.InboxService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInboxServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InboxServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inboxServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("InboxService").Methods()
	return &inboxServiceClient{
		fetchPending: connect.NewClient[ladulasv1.FetchPendingRequest, ladulasv1.FetchPendingResponse](
			httpClient,
			baseURL+InboxServiceFetchPendingProcedure,
			connect.WithSchema(inboxServiceMethods.ByName("FetchPending")),
			connect.WithClientOptions(opts...),
		),
		answerPending: connect.NewClient[ladulasv1.AnswerPendingRequest, ladulasv1.AnswerPendingResponse](
			httpClient,
			baseURL+InboxServiceAnswerPendingProcedure,
			connect.WithSchema(inboxServiceMethods.ByName("AnswerPending")),
			connect.WithClientOptions(opts...),
		),
		reportGrantUse: connect.NewClient[ladulasv1.ReportGrantUseRequest, ladulasv1.ReportGrantUseResponse](
			httpClient,
			baseURL+InboxServiceReportGrantUseProcedure,
			connect.WithSchema(inboxServiceMethods.ByName("ReportGrantUse")),
			connect.WithClientOptions(opts...),
		),
		reconcileGrants: connect.NewClient[ladulasv1.ReconcileGrantsRequest, ladulasv1.ReconcileGrantsResponse](
			httpClient,
			baseURL+InboxServiceReconcileGrantsProcedure,
			connect.WithSchema(inboxServiceMethods.ByName("ReconcileGrants")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inboxServiceClient implements InboxServiceClient.
type inboxServiceClient struct {
	fetchPending    *connect.Client[ladulasv1.FetchPendingRequest, ladulasv1.FetchPendingResponse]
	answerPending   *connect.Client[ladulasv1.AnswerPendingRequest, ladulasv1.AnswerPendingResponse]
	reportGrantUse  *connect.Client[ladulasv1.ReportGrantUseRequest, ladulasv1.ReportGrantUseResponse]
	reconcileGrants *connect.Client[ladulasv1.ReconcileGrantsRequest, ladulasv1.ReconcileGrantsResponse]
}

// FetchPending calls ladulas.v1.InboxService.FetchPending.
func (c *inboxServiceClient) FetchPending(ctx context.Context, req *connect.Request[ladulasv1.FetchPendingRequest]) (*connect.Response[ladulasv1.FetchPendingResponse], error) {
	return c.fetchPending.CallUnary(ctx, req)
}

// AnswerPending calls ladulas.v1.InboxService.AnswerPending.
func (c *inboxServiceClient) AnswerPending(ctx context.Context, req *connect.Request[ladulasv1.AnswerPendingRequest]) (*connect.Response[ladulasv1.AnswerPendingResponse], error) {
	return c.answerPending.CallUnary(ctx, req)
}

// ReportGrantUse calls ladulas.v1.InboxService.ReportGrantUse.
func (c *inboxServiceClient) ReportGrantUse(ctx context.Context, req *connect.Request[ladulasv1.ReportGrantUseRequest]) (*connect.Response[ladulasv1.ReportGrantUseResponse], error) {
	return c.reportGrantUse.CallUnary(ctx, req)
}

// ReconcileGrants calls ladulas.v1.InboxService.ReconcileGrants.
func (c *inboxServiceClient) ReconcileGrants(ctx context.Context, req *connect.Request[ladulasv1.ReconcileGrantsRequest]) (*connect.Response[ladulasv1.ReconcileGrantsResponse], error) {
	return c.reconcileGrants.CallUnary(ctx, req)
}

// InboxServiceHandler is an implementation of the ladulas.v1.InboxService service.
type InboxServiceHandler interface {
	// FetchPending returns the requests this instance is currently waiting on the
	// caller to answer.
	//
	// Wait makes it a long poll. Without one an approval would take as long as
	// the phone's next poll, and with one a phone with the app open is as
	// immediate as a desktop that was dialled — the "live connection" of §11 with
	// the connection pointing the other way.
	FetchPending(context.Context, *connect.Request[ladulasv1.FetchPendingRequest]) (*connect.Response[ladulasv1.FetchPendingResponse], error)
	// AnswerPending settles one of them.
	AnswerPending(context.Context, *connect.Request[ladulasv1.AnswerPendingRequest]) (*connect.Response[ladulasv1.AnswerPendingResponse], error)
	// ReportGrantUse is the requester pushing what it has done, over the link it
	// already holds (decision P).
	//
	// It is served by the approver and called by the requester, which is the
	// opposite of everything else here — and it is the direction that works
	// between two desktops, where the requester dials and the approver listens.
	// An approver that cannot be dialled never receives one; it is told there is
	// something waiting by the flag on a poll's answer, and comes to collect it
	// with ReconcileGrants.
	//
	// Nothing is lost when it fails. The uses stay in the requester's ledger
	// until they are acknowledged, so the push is an optimisation on the pull and
	// never the only way an account gets told.
	ReportGrantUse(context.Context, *connect.Request[ladulasv1.ReportGrantUseRequest]) (*connect.Response[ladulasv1.ReportGrantUseResponse], error)
	// ReconcileGrants brings a delegated grant's two halves back into line
	// (decision P). The approver drives it, in both directions at once: it says
	// which delegations it has taken back, and is told what has been done under
	// the ones it has not.
	//
	// The approver drives because it is the side that can always dial. A phone
	// advertises no address and collects rather than listens, so a requester that
	// had to report in would have nowhere to report to — the same asymmetry the
	// inbox above exists for.
	//
	// Nothing here is load-bearing for a delegation working. One that cannot be
	// reconciled goes on being honoured until it expires, which is the whole
	// point of having handed it over; revocation is best-effort and bounded by
	// the expiry the approver chose when it granted it.
	ReconcileGrants(context.Context, *connect.Request[ladulasv1.ReconcileGrantsRequest]) (*connect.Response[ladulasv1.ReconcileGrantsResponse], error)
}

// NewInboxServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInboxServiceHandler(svc InboxServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inboxServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("InboxService").Methods()
	inboxServiceFetchPendingHandler := connect.NewUnaryHandler(
		InboxServiceFetchPendingProcedure,
		svc.FetchPending,
		connect.WithSchema(inboxServiceMethods.ByName("FetchPending")),
		connect.WithHandlerOptions(opts...),
	)
	inboxServiceAnswerPendingHandler := connect.NewUnaryHandler(
		InboxServiceAnswerPendingProcedure,
		svc.AnswerPending,
		connect.WithSchema(inboxServiceMethods.ByName("AnswerPending")),
		connect.WithHandlerOptions(opts...),
	)
	inboxServiceReportGrantUseHandler := connect.NewUnaryHandler(
		InboxServiceReportGrantUseProcedure,
		svc.ReportGrantUse,
		connect.WithSchema(inboxServiceMethods.ByName("ReportGrantUse")),
		connect.WithHandlerOptions(opts...),
	)
	inboxServiceReconcileGrantsHandler := connect.NewUnaryHandler(
		InboxServiceReconcileGrantsProcedure,
		svc.ReconcileGrants,
		connect.WithSchema(inboxServiceMethods.ByName("ReconcileGrants")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ladulas.v1.InboxService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InboxServiceFetchPendingProcedure:
			inboxServiceFetchPendingHandler.ServeHTTP(w, r)
		case InboxServiceAnswerPendingProcedure:
			inboxServiceAnswerPendingHandler.ServeHTTP(w, r)
		case InboxServiceReportGrantUseProcedure:
			inboxServiceReportGrantUseHandler.ServeHTTP(w, r)
		case InboxServiceReconcileGrantsProcedure:
			inboxServiceReconcileGrantsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInboxServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInboxServiceHandler struct{}

func (UnimplementedInboxServiceHandler) FetchPending(context.Context, *connect.Request[ladulasv1.FetchPendingRequest]) (*connect.Response[ladulasv1.FetchPendingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.InboxService.FetchPending is not implemented"))
}

func (UnimplementedInboxServiceHandler) AnswerPending(context.Context, *connect.Request[ladulasv1.AnswerPendingRequest]) (*connect.Response[ladulasv1.AnswerPendingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.InboxService.AnswerPending is not implemented"))
}

func (UnimplementedInboxServiceHandler) ReportGrantUse(context.Context, *connect.Request[ladulasv1.ReportGrantUseRequest]) (*connect.Response[ladulasv1.ReportGrantUseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.InboxService.ReportGrantUse is not implemented"))
}

func (UnimplementedInboxServiceHandler) ReconcileGrants(context.Context, *connect.Request[ladulasv1.ReconcileGrantsRequest]) (*connect.Response[ladulasv1.ReconcileGrantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.InboxService.ReconcileGrants is not implemented"))
}

// KeyServiceClient is a client for the ladulas.v1.KeyService service.
type KeyServiceClient interface {
	// ListKeys answers what the peer may use, so a keyless agent can respond to
	// SSH_AGENTC_REQUEST_IDENTITIES.
	ListKeys(context.Context, *connect.Request[ladulasv1.ListKeysRequest]) (*connect.Response[ladulasv1.ListKeysResponse], error)
	// RemoteSign performs the signature on the key holder. Implies an approval on
	// the key holder, per its own policy.
	RemoteSign(context.Context, *connect.Request[ladulasv1.RemoteSignRequest]) (*connect.Response[ladulasv1.RemoteSignResponse], error)
	// OfferKey hands a portable key's private half to this peer (decision S).
	//
	// It is the one call in the protocol that carries key material, and it sits
	// here rather than beside the pairing calls because it is about a key. Any
	// paired peer may make it: the directions a trust record grants are about who
	// may ask whom for a signature, and giving somebody a key is neither. What
	// stands in for authorization is at the two ends instead — the sending side
	// re-enters its store passphrase before the call is made, and the key goes
	// nowhere near this store's key list until somebody here has accepted it.
	//
	// The answer says only that the offer is waiting. Acceptance happens whenever
	// the person at this end gets to it, which may be days, and the caller is
	// typically a phone that cannot be called back to be told.
	OfferKey(context.Context, *connect.Request[ladulasv1.OfferKeyRequest]) (*connect.Response[ladulasv1.OfferKeyResponse], error)
	// CollectKeyOffers is OfferKey for a peer that cannot be dialled.
	//
	// A phone never listens, so a key meant for one is queued on the sending
	// instance, the phone is woken, and it comes and asks — the shape a parked
	// approval already has (§11). The two calls are the same transfer from
	// opposite ends, and which one carries a key is decided by which end can be
	// reached rather than by anything about the key.
	//
	// Acknowledgement rides on the next call rather than having one of its own: a
	// collector names the handovers it has written down, and they stop being held
	// for it. A lost response therefore costs a redelivery and never a key —
	// offering the same key twice replaces the earlier offer where it lands.
	CollectKeyOffers(context.Context, *connect.Request[ladulasv1.CollectKeyOffersRequest]) (*connect.Response[ladulasv1.CollectKeyOffersResponse], error)
	// AnnounceKeys is ListKeys for a holder that cannot be dialled (decision T).
	//
	// It is served by the requester and called by the holder, because the holder
	// is the side that can always dial — the same asymmetry, and the same
	// remedy, as the wake-up route a phone announces for itself (§11). The list
	// is what the caller would have answered ListKeys with: what this instance is
	// permitted to use, and no more.
	//
	// The requester remembers it the way it remembers an answer it asked for
	// (decision N), which means an announcement replaces everything remembered
	// about that peer. Nothing here is authorization for anything: it is a peer
	// saying which of its keys exist and may be offered to an agent, and every
	// signature made with one is still decided where the key is.
	AnnounceKeys(context.Context, *connect.Request[ladulasv1.AnnounceKeysRequest]) (*connect.Response[ladulasv1.AnnounceKeysResponse], error)
}

// NewKeyServiceClient constructs a client for the ladulas.v1.KeyService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKeyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) KeyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	keyServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("KeyService").Methods()
	return &keyServiceClient{
		listKeys: connect.NewClient[ladulasv1.ListKeysRequest, ladulasv1.ListKeysResponse](
			httpClient,
			baseURL+KeyServiceListKeysProcedure,
			connect.WithSchema(keyServiceMethods.ByName("ListKeys")),
			connect.WithClientOptions(opts...),
		),
		remoteSign: connect.NewClient[ladulasv1.RemoteSignRequest, ladulasv1.RemoteSignResponse](
			httpClient,
			baseURL+KeyServiceRemoteSignProcedure,
			connect.WithSchema(keyServiceMethods.ByName("RemoteSign")),
			connect.WithClientOptions(opts...),
		),
		offerKey: connect.NewClient[ladulasv1.OfferKeyRequest, ladulasv1.OfferKeyResponse](
			httpClient,
			baseURL+KeyServiceOfferKeyProcedure,
			connect.WithSchema(keyServiceMethods.ByName("OfferKey")),
			connect.WithClientOptions(opts...),
		),
		collectKeyOffers: connect.NewClient[ladulasv1.CollectKeyOffersRequest, ladulasv1.CollectKeyOffersResponse](
			httpClient,
			baseURL+KeyServiceCollectKeyOffersProcedure,
			connect.WithSchema(keyServiceMethods.ByName("CollectKeyOffers")),
			connect.WithClientOptions(opts...),
		),
		announceKeys: connect.NewClient[ladulasv1.AnnounceKeysRequest, ladulasv1.AnnounceKeysResponse](
			httpClient,
			baseURL+KeyServiceAnnounceKeysProcedure,
			connect.WithSchema(keyServiceMethods.ByName("AnnounceKeys")),
			connect.WithClientOptions(opts...),
		),
	}
}

// keyServiceClient implements KeyServiceClient.
type keyServiceClient struct {
	listKeys         *connect.Client[ladulasv1.ListKeysRequest, ladulasv1.ListKeysResponse]
	remoteSign       *connect.Client[ladulasv1.RemoteSignRequest, ladulasv1.RemoteSignResponse]
	offerKey         *connect.Client[ladulasv1.OfferKeyRequest, ladulasv1.OfferKeyResponse]
	collectKeyOffers *connect.Client[ladulasv1.CollectKeyOffersRequest, ladulasv1.CollectKeyOffersResponse]
	announceKeys     *connect.Client[ladulasv1.AnnounceKeysRequest, ladulasv1.AnnounceKeysResponse]
}

// ListKeys calls ladulas.v1.KeyService.ListKeys.
func (c *keyServiceClient) ListKeys(ctx context.Context, req *connect.Request[ladulasv1.ListKeysRequest]) (*connect.Response[ladulasv1.ListKeysResponse], error) {
	return c.listKeys.CallUnary(ctx, req)
}

// RemoteSign calls ladulas.v1.KeyService.RemoteSign.
func (c *keyServiceClient) RemoteSign(ctx context.Context, req *connect.Request[ladulasv1.RemoteSignRequest]) (*connect.Response[ladulasv1.RemoteSignResponse], error) {
	return c.remoteSign.CallUnary(ctx, req)
}

// OfferKey calls ladulas.v1.KeyService.OfferKey.
func (c *keyServiceClient) OfferKey(ctx context.Context, req *connect.Request[ladulasv1.OfferKeyRequest]) (*connect.Response[ladulasv1.OfferKeyResponse], error) {
	return c.offerKey.CallUnary(ctx, req)
}

// CollectKeyOffers calls ladulas.v1.KeyService.CollectKeyOffers.
func (c *keyServiceClient) CollectKeyOffers(ctx context.Context, req *connect.Request[ladulasv1.CollectKeyOffersRequest]) (*connect.Response[ladulasv1.CollectKeyOffersResponse], error) {
	return c.collectKeyOffers.CallUnary(ctx, req)
}

// AnnounceKeys calls ladulas.v1.KeyService.AnnounceKeys.
func (c *keyServiceClient) AnnounceKeys(ctx context.Context, req *connect.Request[ladulasv1.AnnounceKeysRequest]) (*connect.Response[ladulasv1.AnnounceKeysResponse], error) {
	return c.announceKeys.CallUnary(ctx, req)
}

// KeyServiceHandler is an implementation of the ladulas.v1.KeyService service.
type KeyServiceHandler interface {
	// ListKeys answers what the peer may use, so a keyless agent can respond to
	// SSH_AGENTC_REQUEST_IDENTITIES.
	ListKeys(context.Context, *connect.Request[ladulasv1.ListKeysRequest]) (*connect.Response[ladulasv1.ListKeysResponse], error)
	// RemoteSign performs the signature on the key holder. Implies an approval on
	// the key holder, per its own policy.
	RemoteSign(context.Context, *connect.Request[ladulasv1.RemoteSignRequest]) (*connect.Response[ladulasv1.RemoteSignResponse], error)
	// OfferKey hands a portable key's private half to this peer (decision S).
	//
	// It is the one call in the protocol that carries key material, and it sits
	// here rather than beside the pairing calls because it is about a key. Any
	// paired peer may make it: the directions a trust record grants are about who
	// may ask whom for a signature, and giving somebody a key is neither. What
	// stands in for authorization is at the two ends instead — the sending side
	// re-enters its store passphrase before the call is made, and the key goes
	// nowhere near this store's key list until somebody here has accepted it.
	//
	// The answer says only that the offer is waiting. Acceptance happens whenever
	// the person at this end gets to it, which may be days, and the caller is
	// typically a phone that cannot be called back to be told.
	OfferKey(context.Context, *connect.Request[ladulasv1.OfferKeyRequest]) (*connect.Response[ladulasv1.OfferKeyResponse], error)
	// CollectKeyOffers is OfferKey for a peer that cannot be dialled.
	//
	// A phone never listens, so a key meant for one is queued on the sending
	// instance, the phone is woken, and it comes and asks — the shape a parked
	// approval already has (§11). The two calls are the same transfer from
	// opposite ends, and which one carries a key is decided by which end can be
	// reached rather than by anything about the key.
	//
	// Acknowledgement rides on the next call rather than having one of its own: a
	// collector names the handovers it has written down, and they stop being held
	// for it. A lost response therefore costs a redelivery and never a key —
	// offering the same key twice replaces the earlier offer where it lands.
	CollectKeyOffers(context.Context, *connect.Request[ladulasv1.CollectKeyOffersRequest]) (*connect.Response[ladulasv1.CollectKeyOffersResponse], error)
	// AnnounceKeys is ListKeys for a holder that cannot be dialled (decision T).
	//
	// It is served by the requester and called by the holder, because the holder
	// is the side that can always dial — the same asymmetry, and the same
	// remedy, as the wake-up route a phone announces for itself (§11). The list
	// is what the caller would have answered ListKeys with: what this instance is
	// permitted to use, and no more.
	//
	// The requester remembers it the way it remembers an answer it asked for
	// (decision N), which means an announcement replaces everything remembered
	// about that peer. Nothing here is authorization for anything: it is a peer
	// saying which of its keys exist and may be offered to an agent, and every
	// signature made with one is still decided where the key is.
	AnnounceKeys(context.Context, *connect.Request[ladulasv1.AnnounceKeysRequest]) (*connect.Response[ladulasv1.AnnounceKeysResponse], error)
}

// NewKeyServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKeyServiceHandler(svc KeyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	keyServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("KeyService").Methods()
	keyServiceListKeysHandler := connect.NewUnaryHandler(
		KeyServiceListKeysProcedure,
		svc.ListKeys,
		connect.WithSchema(keyServiceMethods.ByName("ListKeys")),
		connect.WithHandlerOptions(opts...),
	)
	keyServiceRemoteSignHandler := connect.NewUnaryHandler(
		KeyServiceRemoteSignProcedure,
		svc.RemoteSign,
		connect.WithSchema(keyServiceMethods.ByName("RemoteSign")),
		connect.WithHandlerOptions(opts...),
	)
	keyServiceOfferKeyHandler := connect.NewUnaryHandler(
		KeyServiceOfferKeyProcedure,
		svc.OfferKey,
		connect.WithSchema(keyServiceMethods.ByName("OfferKey")),
		connect.WithHandlerOptions(opts...),
	)
	keyServiceCollectKeyOffersHandler := connect.NewUnaryHandler(
		KeyServiceCollectKeyOffersProcedure,
		svc.CollectKeyOffers,
		connect.WithSchema(keyServiceMethods.ByName("CollectKeyOffers")),
		connect.WithHandlerOptions(opts...),
	)
	keyServiceAnnounceKeysHandler := connect.NewUnaryHandler(
		KeyServiceAnnounceKeysProcedure,
		svc.AnnounceKeys,
		connect.WithSchema(keyServiceMethods.ByName("AnnounceKeys")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ladulas.v1.KeyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case KeyServiceListKeysProcedure:
			keyServiceListKeysHandler.ServeHTTP(w, r)
		case KeyServiceRemoteSignProcedure:
			keyServiceRemoteSignHandler.ServeHTTP(w, r)
		case KeyServiceOfferKeyProcedure:
			keyServiceOfferKeyHandler.ServeHTTP(w, r)
		case KeyServiceCollectKeyOffersProcedure:
			keyServiceCollectKeyOffersHandler.ServeHTTP(w, r)
		case KeyServiceAnnounceKeysProcedure:
			keyServiceAnnounceKeysHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedKeyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedKeyServiceHandler struct{}

func (UnimplementedKeyServiceHandler) ListKeys(context.Context, *connect.Request[ladulasv1.ListKeysRequest]) (*connect.Response[ladulasv1.ListKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.KeyService.ListKeys is not implemented"))
}

func (UnimplementedKeyServiceHandler) RemoteSign(context.Context, *connect.Request[ladulasv1.RemoteSignRequest]) (*connect.Response[ladulasv1.RemoteSignResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.KeyService.RemoteSign is not implemented"))
}

func (UnimplementedKeyServiceHandler) OfferKey(context.Context, *connect.Request[ladulasv1.OfferKeyRequest]) (*connect.Response[ladulasv1.OfferKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.KeyService.OfferKey is not implemented"))
}

func (UnimplementedKeyServiceHandler) CollectKeyOffers(context.Context, *connect.Request[ladulasv1.CollectKeyOffersRequest]) (*connect.Response[ladulasv1.CollectKeyOffersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.KeyService.CollectKeyOffers is not implemented"))
}

func (UnimplementedKeyServiceHandler) AnnounceKeys(context.Context, *connect.Request[ladulasv1.AnnounceKeysRequest]) (*connect.Response[ladulasv1.AnnounceKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.KeyService.AnnounceKeys is not implemented"))
}

// ProjectServiceClient is a client for the ladulas.v1.ProjectService service.
type ProjectServiceClient interface {
	// ListProjects returns what the caller's peer currently publishes.
	//
	// Publishing is a state rather than an action (decision Q): marking a project
	// published sends nothing, and this is how an approver finds out there is
	// something to read. What comes back describes each project — its name, where
	// it lives, the commit it is at — and not its contents.
	ListProjects(context.Context, *connect.Request[ladulasv1.ListProjectsRequest]) (*connect.Response[ladulasv1.ListProjectsResponse], error)
	// ListDirectory returns one directory, one page at a time.
	//
	// A page rather than a tree, because a tree is unbounded and most of it is
	// never looked at. The caller says where it is and how much it wants; the
	// publisher decides what it is willing to send and says whether there is
	// more.
	ListDirectory(context.Context, *connect.Request[ladulasv1.ListDirectoryRequest]) (*connect.Response[ladulasv1.ListDirectoryResponse], error)
	// SearchProjectFiles finds files by name across a project.
	//
	// "Where is the deployment runbook" is the question people actually have, and
	// walking a directory listing by hand to answer it is not browsing. Paged for
	// the same reason as the listing.
	SearchProjectFiles(context.Context, *connect.Request[ladulasv1.SearchProjectFilesRequest]) (*connect.Response[ladulasv1.SearchProjectFilesResponse], error)
	// FetchProjectFile returns one file's current contents. What an approver
	// keeps is what it has asked for here.
	FetchProjectFile(context.Context, *connect.Request[ladulasv1.FetchProjectFileRequest]) (*connect.Response[ladulasv1.FetchProjectFileResponse], error)
}

// NewProjectServiceClient constructs a client for the ladulas.v1.ProjectService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		listProjects: connect.NewClient[ladulasv1.ListProjectsRequest, ladulasv1.ListProjectsResponse](
			httpClient,
			baseURL+ProjectServiceListProjectsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		listDirectory: connect.NewClient[ladulasv1.ListDirectoryRequest, ladulasv1.ListDirectoryResponse](
			httpClient,
			baseURL+ProjectServiceListDirectoryProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListDirectory")),
			connect.WithClientOptions(opts...),
		),
		searchProjectFiles: connect.NewClient[ladulasv1.SearchProjectFilesRequest, ladulasv1.SearchProjectFilesResponse](
			httpClient,
			baseURL+ProjectServiceSearchProjectFilesProcedure,
			connect.WithSchema(projectServiceMethods.ByName("SearchProjectFiles")),
			connect.WithClientOptions(opts...),
		),
		fetchProjectFile: connect.NewClient[ladulasv1.FetchProjectFileRequest, ladulasv1.FetchProjectFileResponse](
			httpClient,
			baseURL+ProjectServiceFetchProjectFileProcedure,
			connect.WithSchema(projectServiceMethods.ByName("FetchProjectFile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	listProjects       *connect.Client[ladulasv1.ListProjectsRequest, ladulasv1.ListProjectsResponse]
	listDirectory      *connect.Client[ladulasv1.ListDirectoryRequest, ladulasv1.ListDirectoryResponse]
	searchProjectFiles *connect.Client[ladulasv1.SearchProjectFilesRequest, ladulasv1.SearchProjectFilesResponse]
	fetchProjectFile   *connect.Client[ladulasv1.FetchProjectFileRequest, ladulasv1.FetchProjectFileResponse]
}

// ListProjects calls ladulas.v1.ProjectService.ListProjects.
func (c *projectServiceClient) ListProjects(ctx context.Context, req *connect.Request[ladulasv1.ListProjectsRequest]) (*connect.Response[ladulasv1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// ListDirectory calls ladulas.v1.ProjectService.ListDirectory.
func (c *projectServiceClient) ListDirectory(ctx context.Context, req *connect.Request[ladulasv1.ListDirectoryRequest]) (*connect.Response[ladulasv1.ListDirectoryResponse], error) {
	return c.listDirectory.CallUnary(ctx, req)
}

// SearchProjectFiles calls ladulas.v1.ProjectService.SearchProjectFiles.
func (c *projectServiceClient) SearchProjectFiles(ctx context.Context, req *connect.Request[ladulasv1.SearchProjectFilesRequest]) (*connect.Response[ladulasv1.SearchProjectFilesResponse], error) {
	return c.searchProjectFiles.CallUnary(ctx, req)
}

// FetchProjectFile calls ladulas.v1.ProjectService.FetchProjectFile.
func (c *projectServiceClient) FetchProjectFile(ctx context.Context, req *connect.Request[ladulasv1.FetchProjectFileRequest]) (*connect.Response[ladulasv1.FetchProjectFileResponse], error) {
	return c.fetchProjectFile.CallUnary(ctx, req)
}

// ProjectServiceHandler is an implementation of the ladulas.v1.ProjectService service.
type ProjectServiceHandler interface {
	// ListProjects returns what the caller's peer currently publishes.
	//
	// Publishing is a state rather than an action (decision Q): marking a project
	// published sends nothing, and this is how an approver finds out there is
	// something to read. What comes back describes each project — its name, where
	// it lives, the commit it is at — and not its contents.
	ListProjects(context.Context, *connect.Request[ladulasv1.ListProjectsRequest]) (*connect.Response[ladulasv1.ListProjectsResponse], error)
	// ListDirectory returns one directory, one page at a time.
	//
	// A page rather than a tree, because a tree is unbounded and most of it is
	// never looked at. The caller says where it is and how much it wants; the
	// publisher decides what it is willing to send and says whether there is
	// more.
	ListDirectory(context.Context, *connect.Request[ladulasv1.ListDirectoryRequest]) (*connect.Response[ladulasv1.ListDirectoryResponse], error)
	// SearchProjectFiles finds files by name across a project.
	//
	// "Where is the deployment runbook" is the question people actually have, and
	// walking a directory listing by hand to answer it is not browsing. Paged for
	// the same reason as the listing.
	SearchProjectFiles(context.Context, *connect.Request[ladulasv1.SearchProjectFilesRequest]) (*connect.Response[ladulasv1.SearchProjectFilesResponse], error)
	// FetchProjectFile returns one file's current contents. What an approver
	// keeps is what it has asked for here.
	FetchProjectFile(context.Context, *connect.Request[ladulasv1.FetchProjectFileRequest]) (*connect.Response[ladulasv1.FetchProjectFileResponse], error)
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("ProjectService").Methods()
	projectServiceListProjectsHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListDirectoryHandler := connect.NewUnaryHandler(
		ProjectServiceListDirectoryProcedure,
		svc.ListDirectory,
		connect.WithSchema(projectServiceMethods.ByName("ListDirectory")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceSearchProjectFilesHandler := connect.NewUnaryHandler(
		ProjectServiceSearchProjectFilesProcedure,
		svc.SearchProjectFiles,
		connect.WithSchema(projectServiceMethods.ByName("SearchProjectFiles")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceFetchProjectFileHandler := connect.NewUnaryHandler(
		ProjectServiceFetchProjectFileProcedure,
		svc.FetchProjectFile,
		connect.WithSchema(projectServiceMethods.ByName("FetchProjectFile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ladulas.v1.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceListProjectsProcedure:
			projectServiceListProjectsHandler.ServeHTTP(w, r)
		case ProjectServiceListDirectoryProcedure:
			projectServiceListDirectoryHandler.ServeHTTP(w, r)
		case ProjectServiceSearchProjectFilesProcedure:
			projectServiceSearchProjectFilesHandler.ServeHTTP(w, r)
		case ProjectServiceFetchProjectFileProcedure:
			projectServiceFetchProjectFileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) ListProjects(context.Context, *connect.Request[ladulasv1.ListProjectsRequest]) (*connect.Response[ladulasv1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.ProjectService.ListProjects is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListDirectory(context.Context, *connect.Request[ladulasv1.ListDirectoryRequest]) (*connect.Response[ladulasv1.ListDirectoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.ProjectService.ListDirectory is not implemented"))
}

func (UnimplementedProjectServiceHandler) SearchProjectFiles(context.Context, *connect.Request[ladulasv1.SearchProjectFilesRequest]) (*connect.Response[ladulasv1.SearchProjectFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.ProjectService.SearchProjectFiles is not implemented"))
}

func (UnimplementedProjectServiceHandler) FetchProjectFile(context.Context, *connect.Request[ladulasv1.FetchProjectFileRequest]) (*connect.Response[ladulasv1.FetchProjectFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.ProjectService.FetchProjectFile is not implemented"))
}

// PairingServiceClient is a client for the ladulas.v1.PairingService service.
type PairingServiceClient interface {
	// Pair proves the pairing code and returns at once, with a session id both
	// sides record. It does not wait for anybody: the human confirmation is
	// raised behind it and answered whenever the human gets to it.
	Pair(context.Context, *connect.Request[ladulasv1.PairRequest]) (*connect.Response[ladulasv1.PairResponse], error)
	// SettlePairing reconciles one pending pairing. The caller states its own
	// answer so far and is told the callee's; either side may call it, as often
	// as it likes, and the same answer twice changes nothing. It is the only way
	// a pairing completes, and it is how a withdrawal on one side reaches the
	// other.
	SettlePairing(context.Context, *connect.Request[ladulasv1.SettlePairingRequest]) (*connect.Response[ladulasv1.SettlePairingResponse], error)
}

// NewPairingServiceClient constructs a client for the ladulas.v1.PairingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPairingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PairingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pairingServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("PairingService").Methods()
	return &pairingServiceClient{
		pair: connect.NewClient[ladulasv1.PairRequest, ladulasv1.PairResponse](
			httpClient,
			baseURL+PairingServicePairProcedure,
			connect.WithSchema(pairingServiceMethods.ByName("Pair")),
			connect.WithClientOptions(opts...),
		),
		settlePairing: connect.NewClient[ladulasv1.SettlePairingRequest, ladulasv1.SettlePairingResponse](
			httpClient,
			baseURL+PairingServiceSettlePairingProcedure,
			connect.WithSchema(pairingServiceMethods.ByName("SettlePairing")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pairingServiceClient implements PairingServiceClient.
type pairingServiceClient struct {
	pair          *connect.Client[ladulasv1.PairRequest, ladulasv1.PairResponse]
	settlePairing *connect.Client[ladulasv1.SettlePairingRequest, ladulasv1.SettlePairingResponse]
}

// Pair calls ladulas.v1.PairingService.Pair.
func (c *pairingServiceClient) Pair(ctx context.Context, req *connect.Request[ladulasv1.PairRequest]) (*connect.Response[ladulasv1.PairResponse], error) {
	return c.pair.CallUnary(ctx, req)
}

// SettlePairing calls ladulas.v1.PairingService.SettlePairing.
func (c *pairingServiceClient) SettlePairing(ctx context.Context, req *connect.Request[ladulasv1.SettlePairingRequest]) (*connect.Response[ladulasv1.SettlePairingResponse], error) {
	return c.settlePairing.CallUnary(ctx, req)
}

// PairingServiceHandler is an implementation of the ladulas.v1.PairingService service.
type PairingServiceHandler interface {
	// Pair proves the pairing code and returns at once, with a session id both
	// sides record. It does not wait for anybody: the human confirmation is
	// raised behind it and answered whenever the human gets to it.
	Pair(context.Context, *connect.Request[ladulasv1.PairRequest]) (*connect.Response[ladulasv1.PairResponse], error)
	// SettlePairing reconciles one pending pairing. The caller states its own
	// answer so far and is told the callee's; either side may call it, as often
	// as it likes, and the same answer twice changes nothing. It is the only way
	// a pairing completes, and it is how a withdrawal on one side reaches the
	// other.
	SettlePairing(context.Context, *connect.Request[ladulasv1.SettlePairingRequest]) (*connect.Response[ladulasv1.SettlePairingResponse], error)
}

// NewPairingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPairingServiceHandler(svc PairingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pairingServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("PairingService").Methods()
	pairingServicePairHandler := connect.NewUnaryHandler(
		PairingServicePairProcedure,
		svc.Pair,
		connect.WithSchema(pairingServiceMethods.ByName("Pair")),
		connect.WithHandlerOptions(opts...),
	)
	pairingServiceSettlePairingHandler := connect.NewUnaryHandler(
		PairingServiceSettlePairingProcedure,
		svc.SettlePairing,
		connect.WithSchema(pairingServiceMethods.ByName("SettlePairing")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ladulas.v1.PairingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PairingServicePairProcedure:
			pairingServicePairHandler.ServeHTTP(w, r)
		case PairingServiceSettlePairingProcedure:
			pairingServiceSettlePairingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPairingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPairingServiceHandler struct{}

func (UnimplementedPairingServiceHandler) Pair(context.Context, *connect.Request[ladulasv1.PairRequest]) (*connect.Response[ladulasv1.PairResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.PairingService.Pair is not implemented"))
}

func (UnimplementedPairingServiceHandler) SettlePairing(context.Context, *connect.Request[ladulasv1.SettlePairingRequest]) (*connect.Response[ladulasv1.SettlePairingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.PairingService.SettlePairing is not implemented"))
}

// PresenceServiceClient is a client for the ladulas.v1.PresenceService service.
type PresenceServiceClient interface {
	Ping(context.Context, *connect.Request[ladulasv1.PingRequest]) (*connect.Response[ladulasv1.PingResponse], error)
	// Watch holds a connection open and heartbeats over it, so a requester knows
	// whether an approver is reachable before it has anything to ask. The
	// requester reconnects with backoff when the stream breaks.
	Watch(context.Context, *connect.Request[ladulasv1.WatchRequest]) (*connect.ServerStreamForClient[ladulasv1.PresenceEvent], error)
}

// NewPresenceServiceClient constructs a client for the ladulas.v1.PresenceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPresenceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PresenceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	presenceServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("PresenceService").Methods()
	return &presenceServiceClient{
		ping: connect.NewClient[ladulasv1.PingRequest, ladulasv1.PingResponse](
			httpClient,
			baseURL+PresenceServicePingProcedure,
			connect.WithSchema(presenceServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[ladulasv1.WatchRequest, ladulasv1.PresenceEvent](
			httpClient,
			baseURL+PresenceServiceWatchProcedure,
			connect.WithSchema(presenceServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// presenceServiceClient implements PresenceServiceClient.
type presenceServiceClient struct {
	ping  *connect.Client[ladulasv1.PingRequest, ladulasv1.PingResponse]
	watch *connect.Client[ladulasv1.WatchRequest, ladulasv1.PresenceEvent]
}

// Ping calls ladulas.v1.PresenceService.Ping.
func (c *presenceServiceClient) Ping(ctx context.Context, req *connect.Request[ladulasv1.PingRequest]) (*connect.Response[ladulasv1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// Watch calls ladulas.v1.PresenceService.Watch.
func (c *presenceServiceClient) Watch(ctx context.Context, req *connect.Request[ladulasv1.WatchRequest]) (*connect.ServerStreamForClient[ladulasv1.PresenceEvent], error) {
	return c.watch.CallServerStream(ctx, req)
}

// PresenceServiceHandler is an implementation of the ladulas.v1.PresenceService service.
type PresenceServiceHandler interface {
	Ping(context.Context, *connect.Request[ladulasv1.PingRequest]) (*connect.Response[ladulasv1.PingResponse], error)
	// Watch holds a connection open and heartbeats over it, so a requester knows
	// whether an approver is reachable before it has anything to ask. The
	// requester reconnects with backoff when the stream breaks.
	Watch(context.Context, *connect.Request[ladulasv1.WatchRequest], *connect.ServerStream[ladulasv1.PresenceEvent]) error
}

// NewPresenceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPresenceServiceHandler(svc PresenceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	presenceServiceMethods := ladulasv1.File_ladulas_v1_service_proto.Services().ByName("PresenceService").Methods()
	presenceServicePingHandler := connect.NewUnaryHandler(
		PresenceServicePingProcedure,
		svc.Ping,
		connect.WithSchema(presenceServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	presenceServiceWatchHandler := connect.NewServerStreamHandler(
		PresenceServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(presenceServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ladulas.v1.PresenceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PresenceServicePingProcedure:
			presenceServicePingHandler.ServeHTTP(w, r)
		case PresenceServiceWatchProcedure:
			presenceServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPresenceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPresenceServiceHandler struct{}

func (UnimplementedPresenceServiceHandler) Ping(context.Context, *connect.Request[ladulasv1.PingRequest]) (*connect.Response[ladulasv1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.PresenceService.Ping is not implemented"))
}

func (UnimplementedPresenceServiceHandler) Watch(context.Context, *connect.Request[ladulasv1.WatchRequest], *connect.ServerStream[ladulasv1.PresenceEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.PresenceService.Watch is not implemented"))
}
