// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ladulas/v1/wakeup.proto

package ladulasv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	ladulasv1 "github.com/hugowetterberg/ladulas/pkg/protocol/ladulasv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WakeupServiceName is the fully-qualified name of the WakeupService service.
	WakeupServiceName = "ladulas.v1.WakeupService"
	// RelayServiceName is the fully-qualified name of the RelayService service.
	RelayServiceName = "ladulas.v1.RelayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WakeupServiceAnnounceWakeupProcedure is the fully-qualified name of the WakeupService's
	// AnnounceWakeup RPC.
	WakeupServiceAnnounceWakeupProcedure = "/ladulas.v1.WakeupService/AnnounceWakeup"
	// RelayServiceRegisterProcedure is the fully-qualified name of the RelayService's Register RPC.
	RelayServiceRegisterProcedure = "/ladulas.v1.RelayService/Register"
	// RelayServiceWakeProcedure is the fully-qualified name of the RelayService's Wake RPC.
	RelayServiceWakeProcedure = "/ladulas.v1.RelayService/Wake"
)

// WakeupServiceClient is a client for the ladulas.v1.WakeupService service.
type WakeupServiceClient interface {
	// AnnounceWakeup tells a requester how this instance can be woken, or that it
	// cannot be.
	//
	// Idempotent and repeatable. An announcement replaces whatever the requester
	// held for this peer, and one carrying no route withdraws it — which is what
	// switching wake-ups off, and revoking notification permission, both look
	// like from here.
	AnnounceWakeup(context.Context, *connect.Request[ladulasv1.AnnounceWakeupRequest]) (*connect.Response[ladulasv1.AnnounceWakeupResponse], error)
}

// NewWakeupServiceClient constructs a client for the ladulas.v1.WakeupService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWakeupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WakeupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	wakeupServiceMethods := ladulasv1.File_ladulas_v1_wakeup_proto.Services().ByName("WakeupService").Methods()
	return &wakeupServiceClient{
		announceWakeup: connect.NewClient[ladulasv1.AnnounceWakeupRequest, ladulasv1.AnnounceWakeupResponse](
			httpClient,
			baseURL+WakeupServiceAnnounceWakeupProcedure,
			connect.WithSchema(wakeupServiceMethods.ByName("AnnounceWakeup")),
			connect.WithClientOptions(opts...),
		),
	}
}

// wakeupServiceClient implements WakeupServiceClient.
type wakeupServiceClient struct {
	announceWakeup *connect.Client[ladulasv1.AnnounceWakeupRequest, ladulasv1.AnnounceWakeupResponse]
}

// AnnounceWakeup calls ladulas.v1.WakeupService.AnnounceWakeup.
func (c *wakeupServiceClient) AnnounceWakeup(ctx context.Context, req *connect.Request[ladulasv1.AnnounceWakeupRequest]) (*connect.Response[ladulasv1.AnnounceWakeupResponse], error) {
	return c.announceWakeup.CallUnary(ctx, req)
}

// WakeupServiceHandler is an implementation of the ladulas.v1.WakeupService service.
type WakeupServiceHandler interface {
	// AnnounceWakeup tells a requester how this instance can be woken, or that it
	// cannot be.
	//
	// Idempotent and repeatable. An announcement replaces whatever the requester
	// held for this peer, and one carrying no route withdraws it — which is what
	// switching wake-ups off, and revoking notification permission, both look
	// like from here.
	AnnounceWakeup(context.Context, *connect.Request[ladulasv1.AnnounceWakeupRequest]) (*connect.Response[ladulasv1.AnnounceWakeupResponse], error)
}

// NewWakeupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWakeupServiceHandler(svc WakeupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	wakeupServiceMethods := ladulasv1.File_ladulas_v1_wakeup_proto.Services().ByName("WakeupService").Methods()
	wakeupServiceAnnounceWakeupHandler := connect.NewUnaryHandler(
		WakeupServiceAnnounceWakeupProcedure,
		svc.AnnounceWakeup,
		connect.WithSchema(wakeupServiceMethods.ByName("AnnounceWakeup")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ladulas.v1.WakeupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WakeupServiceAnnounceWakeupProcedure:
			wakeupServiceAnnounceWakeupHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWakeupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWakeupServiceHandler struct{}

func (UnimplementedWakeupServiceHandler) AnnounceWakeup(context.Context, *connect.Request[ladulasv1.AnnounceWakeupRequest]) (*connect.Response[ladulasv1.AnnounceWakeupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.WakeupService.AnnounceWakeup is not implemented"))
}

// RelayServiceClient is a client for the ladulas.v1.RelayService service.
type RelayServiceClient interface {
	// Register binds a device token to an instance id.
	Register(context.Context, *connect.Request[ladulasv1.RegisterRequest]) (*connect.Response[ladulasv1.RegisterResponse], error)
	// Wake sends the push.
	Wake(context.Context, *connect.Request[ladulasv1.WakeRequest]) (*connect.Response[ladulasv1.WakeResponse], error)
}

// NewRelayServiceClient constructs a client for the ladulas.v1.RelayService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRelayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RelayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	relayServiceMethods := ladulasv1.File_ladulas_v1_wakeup_proto.Services().ByName("RelayService").Methods()
	return &relayServiceClient{
		register: connect.NewClient[ladulasv1.RegisterRequest, ladulasv1.RegisterResponse](
			httpClient,
			baseURL+RelayServiceRegisterProcedure,
			connect.WithSchema(relayServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		wake: connect.NewClient[ladulasv1.WakeRequest, ladulasv1.WakeResponse](
			httpClient,
			baseURL+RelayServiceWakeProcedure,
			connect.WithSchema(relayServiceMethods.ByName("Wake")),
			connect.WithClientOptions(opts...),
		),
	}
}

// relayServiceClient implements RelayServiceClient.
type relayServiceClient struct {
	register *connect.Client[ladulasv1.RegisterRequest, ladulasv1.RegisterResponse]
	wake     *connect.Client[ladulasv1.WakeRequest, ladulasv1.WakeResponse]
}

// Register calls ladulas.v1.RelayService.Register.
func (c *relayServiceClient) Register(ctx context.Context, req *connect.Request[ladulasv1.RegisterRequest]) (*connect.Response[ladulasv1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Wake calls ladulas.v1.RelayService.Wake.
func (c *relayServiceClient) Wake(ctx context.Context, req *connect.Request[ladulasv1.WakeRequest]) (*connect.Response[ladulasv1.WakeResponse], error) {
	return c.wake.CallUnary(ctx, req)
}

// RelayServiceHandler is an implementation of the ladulas.v1.RelayService service.
type RelayServiceHandler interface {
	// Register binds a device token to an instance id.
	Register(context.Context, *connect.Request[ladulasv1.RegisterRequest]) (*connect.Response[ladulasv1.RegisterResponse], error)
	// Wake sends the push.
	Wake(context.Context, *connect.Request[ladulasv1.WakeRequest]) (*connect.Response[ladulasv1.WakeResponse], error)
}

// NewRelayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRelayServiceHandler(svc RelayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	relayServiceMethods := ladulasv1.File_ladulas_v1_wakeup_proto.Services().ByName("RelayService").Methods()
	relayServiceRegisterHandler := connect.NewUnaryHandler(
		RelayServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(relayServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceWakeHandler := connect.NewUnaryHandler(
		RelayServiceWakeProcedure,
		svc.Wake,
		connect.WithSchema(relayServiceMethods.ByName("Wake")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ladulas.v1.RelayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RelayServiceRegisterProcedure:
			relayServiceRegisterHandler.ServeHTTP(w, r)
		case RelayServiceWakeProcedure:
			relayServiceWakeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRelayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRelayServiceHandler struct{}

func (UnimplementedRelayServiceHandler) Register(context.Context, *connect.Request[ladulasv1.RegisterRequest]) (*connect.Response[ladulasv1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.RelayService.Register is not implemented"))
}

func (UnimplementedRelayServiceHandler) Wake(context.Context, *connect.Request[ladulasv1.WakeRequest]) (*connect.Response[ladulasv1.WakeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ladulas.v1.RelayService.Wake is not implemented"))
}
