// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ladulas/v1/audit.proto

package ladulasv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditEvent is the kind of thing that happened.
type AuditEvent int32

const (
	AuditEvent_AUDIT_EVENT_UNSPECIFIED AuditEvent = 0
	// A request was received and classified.
	AuditEvent_AUDIT_EVENT_REQUEST AuditEvent = 1
	// A decision was reached, by whatever means.
	AuditEvent_AUDIT_EVENT_DECISION AuditEvent = 2
	// A signature was actually produced after an approval.
	AuditEvent_AUDIT_EVENT_SIGNATURE AuditEvent = 3
	// Something failed.
	AuditEvent_AUDIT_EVENT_ERROR AuditEvent = 4
	// A TTL grant was created or revoked.
	AuditEvent_AUDIT_EVENT_GRANT AuditEvent = 5
	// Lifecycle: store unlocked, agent started, key imported.
	AuditEvent_AUDIT_EVENT_LIFECYCLE AuditEvent = 6
	// A portable key was handed to a peer, arrived from one, or was accepted or
	// refused here (§10, decision S).
	//
	// It has an event of its own rather than being lifecycle detail because it is
	// the only thing in Ladulås that cannot be undone. Rotation at the far ends is
	// the only remedy for a key sent wrong, and the question that starts is "what
	// went where, and when" — which is a question a log should be able to answer
	// without anybody grepping for a phrase.
	AuditEvent_AUDIT_EVENT_KEY_TRANSFER AuditEvent = 7
)

// Enum value maps for AuditEvent.
var (
	AuditEvent_name = map[int32]string{
		0: "AUDIT_EVENT_UNSPECIFIED",
		1: "AUDIT_EVENT_REQUEST",
		2: "AUDIT_EVENT_DECISION",
		3: "AUDIT_EVENT_SIGNATURE",
		4: "AUDIT_EVENT_ERROR",
		5: "AUDIT_EVENT_GRANT",
		6: "AUDIT_EVENT_LIFECYCLE",
		7: "AUDIT_EVENT_KEY_TRANSFER",
	}
	AuditEvent_value = map[string]int32{
		"AUDIT_EVENT_UNSPECIFIED":  0,
		"AUDIT_EVENT_REQUEST":      1,
		"AUDIT_EVENT_DECISION":     2,
		"AUDIT_EVENT_SIGNATURE":    3,
		"AUDIT_EVENT_ERROR":        4,
		"AUDIT_EVENT_GRANT":        5,
		"AUDIT_EVENT_LIFECYCLE":    6,
		"AUDIT_EVENT_KEY_TRANSFER": 7,
	}
)

func (x AuditEvent) Enum() *AuditEvent {
	p := new(AuditEvent)
	*p = x
	return p
}

func (x AuditEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_v1_audit_proto_enumTypes[0].Descriptor()
}

func (AuditEvent) Type() protoreflect.EnumType {
	return &file_ladulas_v1_audit_proto_enumTypes[0]
}

func (x AuditEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent.Descriptor instead.
func (AuditEvent) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_v1_audit_proto_rawDescGZIP(), []int{0}
}

// AuditEntry is one line of the append-only JSONL audit log (§18). Entries are
// written with protojson, one per line, on both requester and approver.
//
// Hash chaining the log itself is deferred; the tamper evidence that exists
// today is the approver's signature over each decision, which cannot be forged
// without the approver's identity key.
type AuditEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EntryId   string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Event     AuditEvent             `protobuf:"varint,3,opt,name=event,proto3,enum=ladulas.v1.AuditEvent" json:"event,omitempty"`
	// Correlates every entry belonging to one request.
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The request as evaluated. Present on REQUEST and DECISION entries.
	Request *ApprovalRequest `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	// The decision. Present on DECISION entries.
	Response *ApprovalResponse `protobuf:"bytes,6,opt,name=response,proto3" json:"response,omitempty"`
	// The signed artifact backing the decision, signed by this instance.
	SignedApproval *SignedApproval `protobuf:"bytes,7,opt,name=signed_approval,json=signedApproval,proto3" json:"signed_approval,omitempty"`
	// The approving peer's own signed artifact, when a paired peer decided
	// rather than a human here (§9, §18).
	//
	// This is the part of a requester's log that is evidence rather than its own
	// account of events: it cannot be forged without the approver's identity key,
	// and it covers the exact request bytes that crossed the channel.
	RemoteApproval *SignedApproval `protobuf:"bytes,13,opt,name=remote_approval,json=remoteApproval,proto3" json:"remote_approval,omitempty"`
	// What was shown to the human, when a human decided — the rendered prompt
	// text, so the log records what was actually on screen and not just what the
	// request contained (§9).
	PromptShown string `protobuf:"bytes,8,opt,name=prompt_shown,json=promptShown,proto3" json:"prompt_shown,omitempty"`
	// The documentation label the card carried, when the host that drew it drew
	// one (§6). Present only where a human was asked and the prompt named a
	// project.
	ProjectShown *PresentedProject `protobuf:"bytes,14,opt,name=project_shown,json=projectShown,proto3" json:"project_shown,omitempty"`
	// Free text detail, and the error for ERROR entries.
	Detail string `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	Error  string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	// Fingerprint of the key a SIGNATURE entry used.
	KeyFingerprint string `protobuf:"bytes,11,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	// The grant a GRANT entry concerns.
	Grant         *Grant `protobuf:"bytes,12,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_ladulas_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *AuditEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditEntry) GetEvent() AuditEvent {
	if x != nil {
		return x.Event
	}
	return AuditEvent_AUDIT_EVENT_UNSPECIFIED
}

func (x *AuditEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEntry) GetRequest() *ApprovalRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuditEntry) GetResponse() *ApprovalResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AuditEntry) GetSignedApproval() *SignedApproval {
	if x != nil {
		return x.SignedApproval
	}
	return nil
}

func (x *AuditEntry) GetRemoteApproval() *SignedApproval {
	if x != nil {
		return x.RemoteApproval
	}
	return nil
}

func (x *AuditEntry) GetPromptShown() string {
	if x != nil {
		return x.PromptShown
	}
	return ""
}

func (x *AuditEntry) GetProjectShown() *PresentedProject {
	if x != nil {
		return x.ProjectShown
	}
	return nil
}

func (x *AuditEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AuditEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuditEntry) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

func (x *AuditEntry) GetGrant() *Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

// PresentedProject is the "published documentation" panel as one card carried
// it: which project the change belongs to, and how current what had been read
// of it was (§6).
//
// It is written down rather than worked out again because it cannot be worked
// out again. Every other part of a card is a rendering of the request, and the
// request is in the log — but this sentence is the approver's own state at that
// moment, the pages it happened to hold and the commit they were read at, and
// all of that moves. A record of what somebody was told has to be a record.
type PresentedProject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project, named the way §6 names one: by the peer that publishes it and
	// the identifier both ends derive.
	PeerFingerprint string `protobuf:"bytes,1,opt,name=peer_fingerprint,json=peerFingerprint,proto3" json:"peer_fingerprint,omitempty"`
	ProjectId       string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name            string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Note is the sentence the card showed.
	Note string `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	// Stale says the card was marked: the pages read here were from a commit the
	// change was not built on.
	Stale bool `protobuf:"varint,5,opt,name=stale,proto3" json:"stale,omitempty"`
	// Known says something of the project had been read at the time. A card that
	// named a project nothing had been read of said so, and that is worth keeping
	// too.
	Known         bool `protobuf:"varint,6,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresentedProject) Reset() {
	*x = PresentedProject{}
	mi := &file_ladulas_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentedProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentedProject) ProtoMessage() {}

func (x *PresentedProject) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentedProject.ProtoReflect.Descriptor instead.
func (*PresentedProject) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *PresentedProject) GetPeerFingerprint() string {
	if x != nil {
		return x.PeerFingerprint
	}
	return ""
}

func (x *PresentedProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PresentedProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PresentedProject) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *PresentedProject) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *PresentedProject) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

var File_ladulas_v1_audit_proto protoreflect.FileDescriptor

const file_ladulas_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x16ladulas/v1/audit.proto\x12\n" +
	"ladulas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19ladulas/v1/approval.proto\"\x8f\x05\n" +
	"\n" +
	"AuditEntry\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x05event\x18\x03 \x01(\x0e2\x16.ladulas.v1.AuditEventR\x05event\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x125\n" +
	"\arequest\x18\x05 \x01(\v2\x1b.ladulas.v1.ApprovalRequestR\arequest\x128\n" +
	"\bresponse\x18\x06 \x01(\v2\x1c.ladulas.v1.ApprovalResponseR\bresponse\x12C\n" +
	"\x0fsigned_approval\x18\a \x01(\v2\x1a.ladulas.v1.SignedApprovalR\x0esignedApproval\x12C\n" +
	"\x0fremote_approval\x18\r \x01(\v2\x1a.ladulas.v1.SignedApprovalR\x0eremoteApproval\x12!\n" +
	"\fprompt_shown\x18\b \x01(\tR\vpromptShown\x12A\n" +
	"\rproject_shown\x18\x0e \x01(\v2\x1c.ladulas.v1.PresentedProjectR\fprojectShown\x12\x16\n" +
	"\x06detail\x18\t \x01(\tR\x06detail\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12'\n" +
	"\x0fkey_fingerprint\x18\v \x01(\tR\x0ekeyFingerprint\x12'\n" +
	"\x05grant\x18\f \x01(\v2\x11.ladulas.v1.GrantR\x05grant\"\xb0\x01\n" +
	"\x10PresentedProject\x12)\n" +
	"\x10peer_fingerprint\x18\x01 \x01(\tR\x0fpeerFingerprint\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x14\n" +
	"\x05stale\x18\x05 \x01(\bR\x05stale\x12\x14\n" +
	"\x05known\x18\x06 \x01(\bR\x05known*\xde\x01\n" +
	"\n" +
	"AuditEvent\x12\x1b\n" +
	"\x17AUDIT_EVENT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AUDIT_EVENT_REQUEST\x10\x01\x12\x18\n" +
	"\x14AUDIT_EVENT_DECISION\x10\x02\x12\x19\n" +
	"\x15AUDIT_EVENT_SIGNATURE\x10\x03\x12\x15\n" +
	"\x11AUDIT_EVENT_ERROR\x10\x04\x12\x15\n" +
	"\x11AUDIT_EVENT_GRANT\x10\x05\x12\x19\n" +
	"\x15AUDIT_EVENT_LIFECYCLE\x10\x06\x12\x1c\n" +
	"\x18AUDIT_EVENT_KEY_TRANSFER\x10\aBDZBgithub.com/hugowetterberg/ladulas/pkg/protocol/ladulasv1;ladulasv1b\x06proto3"

var (
	file_ladulas_v1_audit_proto_rawDescOnce sync.Once
	file_ladulas_v1_audit_proto_rawDescData []byte
)

func file_ladulas_v1_audit_proto_rawDescGZIP() []byte {
	file_ladulas_v1_audit_proto_rawDescOnce.Do(func() {
		file_ladulas_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ladulas_v1_audit_proto_rawDesc), len(file_ladulas_v1_audit_proto_rawDesc)))
	})
	return file_ladulas_v1_audit_proto_rawDescData
}

var file_ladulas_v1_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ladulas_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ladulas_v1_audit_proto_goTypes = []any{
	(AuditEvent)(0),               // 0: ladulas.v1.AuditEvent
	(*AuditEntry)(nil),            // 1: ladulas.v1.AuditEntry
	(*PresentedProject)(nil),      // 2: ladulas.v1.PresentedProject
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*ApprovalRequest)(nil),       // 4: ladulas.v1.ApprovalRequest
	(*ApprovalResponse)(nil),      // 5: ladulas.v1.ApprovalResponse
	(*SignedApproval)(nil),        // 6: ladulas.v1.SignedApproval
	(*Grant)(nil),                 // 7: ladulas.v1.Grant
}
var file_ladulas_v1_audit_proto_depIdxs = []int32{
	3, // 0: ladulas.v1.AuditEntry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: ladulas.v1.AuditEntry.event:type_name -> ladulas.v1.AuditEvent
	4, // 2: ladulas.v1.AuditEntry.request:type_name -> ladulas.v1.ApprovalRequest
	5, // 3: ladulas.v1.AuditEntry.response:type_name -> ladulas.v1.ApprovalResponse
	6, // 4: ladulas.v1.AuditEntry.signed_approval:type_name -> ladulas.v1.SignedApproval
	6, // 5: ladulas.v1.AuditEntry.remote_approval:type_name -> ladulas.v1.SignedApproval
	2, // 6: ladulas.v1.AuditEntry.project_shown:type_name -> ladulas.v1.PresentedProject
	7, // 7: ladulas.v1.AuditEntry.grant:type_name -> ladulas.v1.Grant
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_ladulas_v1_audit_proto_init() }
func file_ladulas_v1_audit_proto_init() {
	if File_ladulas_v1_audit_proto != nil {
		return
	}
	file_ladulas_v1_approval_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ladulas_v1_audit_proto_rawDesc), len(file_ladulas_v1_audit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ladulas_v1_audit_proto_goTypes,
		DependencyIndexes: file_ladulas_v1_audit_proto_depIdxs,
		EnumInfos:         file_ladulas_v1_audit_proto_enumTypes,
		MessageInfos:      file_ladulas_v1_audit_proto_msgTypes,
	}.Build()
	File_ladulas_v1_audit_proto = out.File
	file_ladulas_v1_audit_proto_goTypes = nil
	file_ladulas_v1_audit_proto_depIdxs = nil
}
