// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ladulas/v1/policy.proto

package ladulasv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action is what a rule does to a matching request.
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	// Ask a human. The default for everything.
	Action_ACTION_PROMPT Action = 1
	// Approve without asking. Approvers still get a passive notification unless
	// notify is explicitly disabled (§9).
	Action_ACTION_APPROVE Action = 2
	Action_ACTION_DENY    Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_PROMPT",
		2: "ACTION_APPROVE",
		3: "ACTION_DENY",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_PROMPT":      1,
		"ACTION_APPROVE":     2,
		"ACTION_DENY":        3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_v1_policy_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_ladulas_v1_policy_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_v1_policy_proto_rawDescGZIP(), []int{0}
}

// Tristate lets a rule require a boolean condition, forbid it, or ignore it.
type Tristate int32

const (
	Tristate_TRISTATE_ANY   Tristate = 0
	Tristate_TRISTATE_TRUE  Tristate = 1
	Tristate_TRISTATE_FALSE Tristate = 2
)

// Enum value maps for Tristate.
var (
	Tristate_name = map[int32]string{
		0: "TRISTATE_ANY",
		1: "TRISTATE_TRUE",
		2: "TRISTATE_FALSE",
	}
	Tristate_value = map[string]int32{
		"TRISTATE_ANY":   0,
		"TRISTATE_TRUE":  1,
		"TRISTATE_FALSE": 2,
	}
)

func (x Tristate) Enum() *Tristate {
	p := new(Tristate)
	*p = x
	return p
}

func (x Tristate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tristate) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_v1_policy_proto_enumTypes[1].Descriptor()
}

func (Tristate) Type() protoreflect.EnumType {
	return &file_ladulas_v1_policy_proto_enumTypes[1]
}

func (x Tristate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tristate.Descriptor instead.
func (Tristate) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_v1_policy_proto_rawDescGZIP(), []int{1}
}

// Match selects requests. All populated fields must match; within a repeated
// field any element matching is enough. String lists are matched with shell
// glob patterns, case insensitively for host names.
type Match struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kinds           []RequestKind          `protobuf:"varint,1,rep,packed,name=kinds,proto3,enum=ladulas.v1.RequestKind" json:"kinds,omitempty"`
	KeyFingerprints []string               `protobuf:"bytes,2,rep,name=key_fingerprints,json=keyFingerprints,proto3" json:"key_fingerprints,omitempty"`
	KeyLabels       []string               `protobuf:"bytes,3,rep,name=key_labels,json=keyLabels,proto3" json:"key_labels,omitempty"`
	// Destination host name or fingerprint for SSH auth requests.
	Destinations []string `protobuf:"bytes,4,rep,name=destinations,proto3" json:"destinations,omitempty"`
	// Remote username for SSH auth requests.
	Usernames []string `protobuf:"bytes,5,rep,name=usernames,proto3" json:"usernames,omitempty"`
	// Repository path or origin URL for git signing requests.
	Repositories []string `protobuf:"bytes,6,rep,name=repositories,proto3" json:"repositories,omitempty"`
	// SSHSIG namespace.
	Namespaces         []string `protobuf:"bytes,7,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	RequesterInstances []string `protobuf:"bytes,8,rep,name=requester_instances,json=requesterInstances,proto3" json:"requester_instances,omitempty"`
	// Executable path of the local process behind the agent socket.
	Executables []string `protobuf:"bytes,9,rep,name=executables,proto3" json:"executables,omitempty"`
	// Whether the request arrived over a forwarded agent connection.
	Forwarded Tristate `protobuf:"varint,20,opt,name=forwarded,proto3,enum=ladulas.v1.Tristate" json:"forwarded,omitempty"`
	// Whether the request could be tied to a session-bind entry.
	Bound Tristate `protobuf:"varint,21,opt,name=bound,proto3,enum=ladulas.v1.Tristate" json:"bound,omitempty"`
	// Whether the requester is this instance.
	Local         Tristate `protobuf:"varint,22,opt,name=local,proto3,enum=ladulas.v1.Tristate" json:"local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_ladulas_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetKinds() []RequestKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Match) GetKeyFingerprints() []string {
	if x != nil {
		return x.KeyFingerprints
	}
	return nil
}

func (x *Match) GetKeyLabels() []string {
	if x != nil {
		return x.KeyLabels
	}
	return nil
}

func (x *Match) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *Match) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *Match) GetRepositories() []string {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *Match) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Match) GetRequesterInstances() []string {
	if x != nil {
		return x.RequesterInstances
	}
	return nil
}

func (x *Match) GetExecutables() []string {
	if x != nil {
		return x.Executables
	}
	return nil
}

func (x *Match) GetForwarded() Tristate {
	if x != nil {
		return x.Forwarded
	}
	return Tristate_TRISTATE_ANY
}

func (x *Match) GetBound() Tristate {
	if x != nil {
		return x.Bound
	}
	return Tristate_TRISTATE_ANY
}

func (x *Match) GetLocal() Tristate {
	if x != nil {
		return x.Local
	}
	return Tristate_TRISTATE_ANY
}

// Rule is one policy entry. Rules are evaluated in order and the first match
// wins, so put specific denials above general approvals.
type Rule struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Match       *Match                 `protobuf:"bytes,3,opt,name=match,proto3" json:"match,omitempty"`
	Action      Action                 `protobuf:"varint,4,opt,name=action,proto3,enum=ladulas.v1.Action" json:"action,omitempty"`
	// Show a passive notification when this rule auto-approves. Defaults to true
	// for ACTION_APPROVE; set explicitly to false to silence it.
	Notify        *bool `protobuf:"varint,5,opt,name=notify,proto3,oneof" json:"notify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_ladulas_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *Rule) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Rule) GetNotify() bool {
	if x != nil && x.Notify != nil {
		return *x.Notify
	}
	return false
}

// Defaults cover requests no rule matched.
type Defaults struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What to do with an SSH auth request that carries no session-bind context,
	// i.e. an unknown destination. Defaults to ACTION_PROMPT.
	UnboundSshAuth Action `protobuf:"varint,1,opt,name=unbound_ssh_auth,json=unboundSshAuth,proto3,enum=ladulas.v1.Action" json:"unbound_ssh_auth,omitempty"`
	// What to do with anything else no rule matched. Defaults to ACTION_PROMPT.
	Fallback Action `protobuf:"varint,2,opt,name=fallback,proto3,enum=ladulas.v1.Action" json:"fallback,omitempty"`
	// How long to wait for an answer. SSH auth is bounded by the far server's
	// LoginGraceTime, typically 120s, so the default is 90s; git signing blocks
	// happily and gets an hour, which is a budget for somebody who is not at the
	// desk rather than one for somebody who is (§9).
	SshAuthTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=ssh_auth_timeout,json=sshAuthTimeout,proto3" json:"ssh_auth_timeout,omitempty"`
	SignTimeout    *durationpb.Duration `protobuf:"bytes,4,opt,name=sign_timeout,json=signTimeout,proto3" json:"sign_timeout,omitempty"`
	// TTL offered by the "approve for a while" buttons on the prompt.
	GrantTtlOptions []*durationpb.Duration `protobuf:"bytes,5,rep,name=grant_ttl_options,json=grantTtlOptions,proto3" json:"grant_ttl_options,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Defaults) Reset() {
	*x = Defaults{}
	mi := &file_ladulas_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Defaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Defaults) ProtoMessage() {}

func (x *Defaults) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Defaults.ProtoReflect.Descriptor instead.
func (*Defaults) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *Defaults) GetUnboundSshAuth() Action {
	if x != nil {
		return x.UnboundSshAuth
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Defaults) GetFallback() Action {
	if x != nil {
		return x.Fallback
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Defaults) GetSshAuthTimeout() *durationpb.Duration {
	if x != nil {
		return x.SshAuthTimeout
	}
	return nil
}

func (x *Defaults) GetSignTimeout() *durationpb.Duration {
	if x != nil {
		return x.SignTimeout
	}
	return nil
}

func (x *Defaults) GetGrantTtlOptions() []*durationpb.Duration {
	if x != nil {
		return x.GrantTtlOptions
	}
	return nil
}

// PolicyDocument is the on-disk policy, stored as protojson so it stays
// hand-editable and typed at once.
type PolicyDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Defaults      *Defaults              `protobuf:"bytes,2,opt,name=defaults,proto3" json:"defaults,omitempty"`
	Rules         []*Rule                `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyDocument) Reset() {
	*x = PolicyDocument{}
	mi := &file_ladulas_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDocument) ProtoMessage() {}

func (x *PolicyDocument) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDocument.ProtoReflect.Descriptor instead.
func (*PolicyDocument) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyDocument) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyDocument) GetDefaults() *Defaults {
	if x != nil {
		return x.Defaults
	}
	return nil
}

func (x *PolicyDocument) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_ladulas_v1_policy_proto protoreflect.FileDescriptor

const file_ladulas_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x17ladulas/v1/policy.proto\x12\n" +
	"ladulas.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x19ladulas/v1/approval.proto\"\xe5\x03\n" +
	"\x05Match\x12-\n" +
	"\x05kinds\x18\x01 \x03(\x0e2\x17.ladulas.v1.RequestKindR\x05kinds\x12)\n" +
	"\x10key_fingerprints\x18\x02 \x03(\tR\x0fkeyFingerprints\x12\x1d\n" +
	"\n" +
	"key_labels\x18\x03 \x03(\tR\tkeyLabels\x12\"\n" +
	"\fdestinations\x18\x04 \x03(\tR\fdestinations\x12\x1c\n" +
	"\tusernames\x18\x05 \x03(\tR\tusernames\x12\"\n" +
	"\frepositories\x18\x06 \x03(\tR\frepositories\x12\x1e\n" +
	"\n" +
	"namespaces\x18\a \x03(\tR\n" +
	"namespaces\x12/\n" +
	"\x13requester_instances\x18\b \x03(\tR\x12requesterInstances\x12 \n" +
	"\vexecutables\x18\t \x03(\tR\vexecutables\x122\n" +
	"\tforwarded\x18\x14 \x01(\x0e2\x14.ladulas.v1.TristateR\tforwarded\x12*\n" +
	"\x05bound\x18\x15 \x01(\x0e2\x14.ladulas.v1.TristateR\x05bound\x12*\n" +
	"\x05local\x18\x16 \x01(\x0e2\x14.ladulas.v1.TristateR\x05local\"\xb9\x01\n" +
	"\x04Rule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x05match\x18\x03 \x01(\v2\x11.ladulas.v1.MatchR\x05match\x12*\n" +
	"\x06action\x18\x04 \x01(\x0e2\x12.ladulas.v1.ActionR\x06action\x12\x1b\n" +
	"\x06notify\x18\x05 \x01(\bH\x00R\x06notify\x88\x01\x01B\t\n" +
	"\a_notify\"\xc2\x02\n" +
	"\bDefaults\x12<\n" +
	"\x10unbound_ssh_auth\x18\x01 \x01(\x0e2\x12.ladulas.v1.ActionR\x0eunboundSshAuth\x12.\n" +
	"\bfallback\x18\x02 \x01(\x0e2\x12.ladulas.v1.ActionR\bfallback\x12C\n" +
	"\x10ssh_auth_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0esshAuthTimeout\x12<\n" +
	"\fsign_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vsignTimeout\x12E\n" +
	"\x11grant_ttl_options\x18\x05 \x03(\v2\x19.google.protobuf.DurationR\x0fgrantTtlOptions\"\x84\x01\n" +
	"\x0ePolicyDocument\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x120\n" +
	"\bdefaults\x18\x02 \x01(\v2\x14.ladulas.v1.DefaultsR\bdefaults\x12&\n" +
	"\x05rules\x18\x03 \x03(\v2\x10.ladulas.v1.RuleR\x05rules*X\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_PROMPT\x10\x01\x12\x12\n" +
	"\x0eACTION_APPROVE\x10\x02\x12\x0f\n" +
	"\vACTION_DENY\x10\x03*C\n" +
	"\bTristate\x12\x10\n" +
	"\fTRISTATE_ANY\x10\x00\x12\x11\n" +
	"\rTRISTATE_TRUE\x10\x01\x12\x12\n" +
	"\x0eTRISTATE_FALSE\x10\x02BDZBgithub.com/hugowetterberg/ladulas/pkg/protocol/ladulasv1;ladulasv1b\x06proto3"

var (
	file_ladulas_v1_policy_proto_rawDescOnce sync.Once
	file_ladulas_v1_policy_proto_rawDescData []byte
)

func file_ladulas_v1_policy_proto_rawDescGZIP() []byte {
	file_ladulas_v1_policy_proto_rawDescOnce.Do(func() {
		file_ladulas_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ladulas_v1_policy_proto_rawDesc), len(file_ladulas_v1_policy_proto_rawDesc)))
	})
	return file_ladulas_v1_policy_proto_rawDescData
}

var file_ladulas_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ladulas_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ladulas_v1_policy_proto_goTypes = []any{
	(Action)(0),                 // 0: ladulas.v1.Action
	(Tristate)(0),               // 1: ladulas.v1.Tristate
	(*Match)(nil),               // 2: ladulas.v1.Match
	(*Rule)(nil),                // 3: ladulas.v1.Rule
	(*Defaults)(nil),            // 4: ladulas.v1.Defaults
	(*PolicyDocument)(nil),      // 5: ladulas.v1.PolicyDocument
	(RequestKind)(0),            // 6: ladulas.v1.RequestKind
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
}
var file_ladulas_v1_policy_proto_depIdxs = []int32{
	6,  // 0: ladulas.v1.Match.kinds:type_name -> ladulas.v1.RequestKind
	1,  // 1: ladulas.v1.Match.forwarded:type_name -> ladulas.v1.Tristate
	1,  // 2: ladulas.v1.Match.bound:type_name -> ladulas.v1.Tristate
	1,  // 3: ladulas.v1.Match.local:type_name -> ladulas.v1.Tristate
	2,  // 4: ladulas.v1.Rule.match:type_name -> ladulas.v1.Match
	0,  // 5: ladulas.v1.Rule.action:type_name -> ladulas.v1.Action
	0,  // 6: ladulas.v1.Defaults.unbound_ssh_auth:type_name -> ladulas.v1.Action
	0,  // 7: ladulas.v1.Defaults.fallback:type_name -> ladulas.v1.Action
	7,  // 8: ladulas.v1.Defaults.ssh_auth_timeout:type_name -> google.protobuf.Duration
	7,  // 9: ladulas.v1.Defaults.sign_timeout:type_name -> google.protobuf.Duration
	7,  // 10: ladulas.v1.Defaults.grant_ttl_options:type_name -> google.protobuf.Duration
	4,  // 11: ladulas.v1.PolicyDocument.defaults:type_name -> ladulas.v1.Defaults
	3,  // 12: ladulas.v1.PolicyDocument.rules:type_name -> ladulas.v1.Rule
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ladulas_v1_policy_proto_init() }
func file_ladulas_v1_policy_proto_init() {
	if File_ladulas_v1_policy_proto != nil {
		return
	}
	file_ladulas_v1_approval_proto_init()
	file_ladulas_v1_policy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ladulas_v1_policy_proto_rawDesc), len(file_ladulas_v1_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ladulas_v1_policy_proto_goTypes,
		DependencyIndexes: file_ladulas_v1_policy_proto_depIdxs,
		EnumInfos:         file_ladulas_v1_policy_proto_enumTypes,
		MessageInfos:      file_ladulas_v1_policy_proto_msgTypes,
	}.Build()
	File_ladulas_v1_policy_proto = out.File
	file_ladulas_v1_policy_proto_goTypes = nil
	file_ladulas_v1_policy_proto_depIdxs = nil
}
