// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ladulas/v1/project.proto

// Project publishing and browsing (§6, decision Q). A requester marks a project
// as published to the peers that approve for it, and marking it sends nothing;
// an approver that wants to read one asks — for the projects on offer, for a
// directory at a time, for a name across the whole of it, and for the files it
// opens — and keeps what it has read.
//
// Everything here is requester-asserted display content and nothing else. It is
// never evidence about a signature, it is rendered as untrusted text by the
// shared viewer (§12), and the caps that bound it exist because an approver's
// disk and an approver's patience are both finite.

package ladulasv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Publication is a project on offer: what it is called, where it lives on the
// requester, and what commit it is at.
//
// It is the whole of what publishing carries. The contents are read a call at a
// time by whoever wants them, so a publication that nobody opens costs one
// record on the machine that made it and nothing anywhere else.
type Publication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable across publications of the same project, derived from the origin URL
	// and the repository path so that the requester and the approver arrive at it
	// independently — which is what lets a signing request name a project without
	// carrying one.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Where the project lives on the requester.
	Path      string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	OriginUrl string `protobuf:"bytes,4,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`
	// The branch and commit the project is at. They are re-read every time the
	// project is listed rather than frozen at publication, because the commit is
	// what the staleness label compares a signing request against and a machine
	// that has been committing all afternoon has moved.
	Branch string `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit string `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
	// When the project was first marked published.
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publication) Reset() {
	*x = Publication{}
	mi := &file_ladulas_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication) ProtoMessage() {}

func (x *Publication) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication.ProtoReflect.Descriptor instead.
func (*Publication) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Publication) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Publication) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Publication) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Publication) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

func (x *Publication) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Publication) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Publication) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// ProjectEntry is one thing in a directory, as an approver sees it.
type ProjectEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The path relative to the project root, which is what every other call
	// takes.
	Path      string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Directory bool                   `protobuf:"varint,3,opt,name=directory,proto3" json:"directory,omitempty"`
	Size      int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Modified  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	// Whether the publisher would serve the contents. A file too large for the
	// caps, or of a kind that is not offered, is still listed — a browser that
	// silently omitted it would be lying about what the project contains.
	Readable bool `protobuf:"varint,6,opt,name=readable,proto3" json:"readable,omitempty"`
	// Why not, when it is not.
	Reason string `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	// For a directory: nothing anywhere beneath it is a file this instance would
	// serve. It answers the question a browser cannot answer for itself without a
	// call per folder — the publisher is walking its own disk, an approver would
	// be walking it down a network — and it is what lets a viewer that shows only
	// what it can read leave out the folders that lead nowhere.
	//
	// It is stated the empty way round on purpose. A publisher that has never
	// heard of the field sends nothing, which reads as false, and a browser that
	// hides on true then hides nothing rather than hiding every folder there is.
	// A walk that hits its own cap before finding anything reports false for the
	// same reason: not knowing is not the same as knowing there is nothing.
	NothingReadable bool `protobuf:"varint,8,opt,name=nothing_readable,json=nothingReadable,proto3" json:"nothing_readable,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectEntry) Reset() {
	*x = ProjectEntry{}
	mi := &file_ladulas_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEntry) ProtoMessage() {}

func (x *ProjectEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEntry.ProtoReflect.Descriptor instead.
func (*ProjectEntry) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProjectEntry) GetDirectory() bool {
	if x != nil {
		return x.Directory
	}
	return false
}

func (x *ProjectEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProjectEntry) GetModified() *timestamppb.Timestamp {
	if x != nil {
		return x.Modified
	}
	return nil
}

func (x *ProjectEntry) GetReadable() bool {
	if x != nil {
		return x.Readable
	}
	return false
}

func (x *ProjectEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProjectEntry) GetNothingReadable() bool {
	if x != nil {
		return x.NothingReadable
	}
	return false
}

var File_ladulas_v1_project_proto protoreflect.FileDescriptor

const file_ladulas_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x18ladulas/v1/project.proto\x12\n" +
	"ladulas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\vPublication\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"origin_url\x18\x04 \x01(\tR\toriginUrl\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x16\n" +
	"\x06commit\x18\x06 \x01(\tR\x06commit\x12=\n" +
	"\fpublished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\"\xff\x01\n" +
	"\fProjectEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\tdirectory\x18\x03 \x01(\bR\tdirectory\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x126\n" +
	"\bmodified\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bmodified\x12\x1a\n" +
	"\breadable\x18\x06 \x01(\bR\breadable\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12)\n" +
	"\x10nothing_readable\x18\b \x01(\bR\x0fnothingReadableBDZBgithub.com/hugowetterberg/ladulas/pkg/protocol/ladulasv1;ladulasv1b\x06proto3"

var (
	file_ladulas_v1_project_proto_rawDescOnce sync.Once
	file_ladulas_v1_project_proto_rawDescData []byte
)

func file_ladulas_v1_project_proto_rawDescGZIP() []byte {
	file_ladulas_v1_project_proto_rawDescOnce.Do(func() {
		file_ladulas_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ladulas_v1_project_proto_rawDesc), len(file_ladulas_v1_project_proto_rawDesc)))
	})
	return file_ladulas_v1_project_proto_rawDescData
}

var file_ladulas_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ladulas_v1_project_proto_goTypes = []any{
	(*Publication)(nil),           // 0: ladulas.v1.Publication
	(*ProjectEntry)(nil),          // 1: ladulas.v1.ProjectEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_ladulas_v1_project_proto_depIdxs = []int32{
	2, // 0: ladulas.v1.Publication.published_at:type_name -> google.protobuf.Timestamp
	2, // 1: ladulas.v1.ProjectEntry.modified:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ladulas_v1_project_proto_init() }
func file_ladulas_v1_project_proto_init() {
	if File_ladulas_v1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ladulas_v1_project_proto_rawDesc), len(file_ladulas_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ladulas_v1_project_proto_goTypes,
		DependencyIndexes: file_ladulas_v1_project_proto_depIdxs,
		MessageInfos:      file_ladulas_v1_project_proto_msgTypes,
	}.Build()
	File_ladulas_v1_project_proto = out.File
	file_ladulas_v1_project_proto_goTypes = nil
	file_ladulas_v1_project_proto_depIdxs = nil
}
