// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ladulas/v1/wakeup.proto

package ladulasv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WakeupKind is how a wake-up reaches a device. Only the publisher-hosted relay
// exists; UnifiedPush is the deferred option §11 describes and would be the next
// value rather than a second field.
type WakeupKind int32

const (
	WakeupKind_WAKEUP_KIND_UNSPECIFIED WakeupKind = 0
	WakeupKind_WAKEUP_KIND_RELAY       WakeupKind = 1
)

// Enum value maps for WakeupKind.
var (
	WakeupKind_name = map[int32]string{
		0: "WAKEUP_KIND_UNSPECIFIED",
		1: "WAKEUP_KIND_RELAY",
	}
	WakeupKind_value = map[string]int32{
		"WAKEUP_KIND_UNSPECIFIED": 0,
		"WAKEUP_KIND_RELAY":       1,
	}
)

func (x WakeupKind) Enum() *WakeupKind {
	p := new(WakeupKind)
	*p = x
	return p
}

func (x WakeupKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WakeupKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_v1_wakeup_proto_enumTypes[0].Descriptor()
}

func (WakeupKind) Type() protoreflect.EnumType {
	return &file_ladulas_v1_wakeup_proto_enumTypes[0]
}

func (x WakeupKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WakeupKind.Descriptor instead.
func (WakeupKind) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{0}
}

// PushPlatform is which vendor's push service a token belongs to. FCM arrives
// with Android (M10) and is a value here rather than a second relay.
type PushPlatform int32

const (
	PushPlatform_PUSH_PLATFORM_UNSPECIFIED PushPlatform = 0
	PushPlatform_PUSH_PLATFORM_APNS        PushPlatform = 1
	PushPlatform_PUSH_PLATFORM_FCM         PushPlatform = 2
)

// Enum value maps for PushPlatform.
var (
	PushPlatform_name = map[int32]string{
		0: "PUSH_PLATFORM_UNSPECIFIED",
		1: "PUSH_PLATFORM_APNS",
		2: "PUSH_PLATFORM_FCM",
	}
	PushPlatform_value = map[string]int32{
		"PUSH_PLATFORM_UNSPECIFIED": 0,
		"PUSH_PLATFORM_APNS":        1,
		"PUSH_PLATFORM_FCM":         2,
	}
)

func (x PushPlatform) Enum() *PushPlatform {
	p := new(PushPlatform)
	*p = x
	return p
}

func (x PushPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_v1_wakeup_proto_enumTypes[1].Descriptor()
}

func (PushPlatform) Type() protoreflect.EnumType {
	return &file_ladulas_v1_wakeup_proto_enumTypes[1]
}

func (x PushPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushPlatform.Descriptor instead.
func (PushPlatform) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{1}
}

// WakeStyle is what the push should do when it arrives.
type WakeStyle int32

const (
	WakeStyle_WAKE_STYLE_UNSPECIFIED WakeStyle = 0
	// A visible alert. The default, and the only one that reaches a human.
	WakeStyle_WAKE_STYLE_ALERT WakeStyle = 1
	// A silent background wake, for a request the approver has already promised
	// to answer (§20, M9). It is throttled by the platform, works only while the
	// app is resident, and is followed by the alert when it does not land.
	WakeStyle_WAKE_STYLE_SILENT WakeStyle = 2
)

// Enum value maps for WakeStyle.
var (
	WakeStyle_name = map[int32]string{
		0: "WAKE_STYLE_UNSPECIFIED",
		1: "WAKE_STYLE_ALERT",
		2: "WAKE_STYLE_SILENT",
	}
	WakeStyle_value = map[string]int32{
		"WAKE_STYLE_UNSPECIFIED": 0,
		"WAKE_STYLE_ALERT":       1,
		"WAKE_STYLE_SILENT":      2,
	}
)

func (x WakeStyle) Enum() *WakeStyle {
	p := new(WakeStyle)
	*p = x
	return p
}

func (x WakeStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WakeStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_v1_wakeup_proto_enumTypes[2].Descriptor()
}

func (WakeStyle) Type() protoreflect.EnumType {
	return &file_ladulas_v1_wakeup_proto_enumTypes[2]
}

func (x WakeStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WakeStyle.Descriptor instead.
func (WakeStyle) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{2}
}

// WakeSubject is which of the two fixed sentences the relay should send.
//
// It is the one thing beyond timing a relay learns about what is happening, and
// it is one bit: somebody is being asked to sign, or somebody is being handed a
// key (§10, decision S). The alternative was worse in both directions — a phone
// told "Signing request pending" when a key is waiting is being lied to, and a
// key handover that could only be collected the next time the app happened to
// open is a feature that works when nobody is watching for it.
//
// It stays an enum rather than a string for the reason the payload has no
// request data in it at all: what the relay can send is a list this repository
// wrote, not something a caller composes.
type WakeSubject int32

const (
	// Unset means an approval, which is what every wake-up was before there was
	// anything else to be woken for.
	WakeSubject_WAKE_SUBJECT_UNSPECIFIED WakeSubject = 0
	WakeSubject_WAKE_SUBJECT_APPROVAL    WakeSubject = 1
	WakeSubject_WAKE_SUBJECT_KEY_OFFER   WakeSubject = 2
)

// Enum value maps for WakeSubject.
var (
	WakeSubject_name = map[int32]string{
		0: "WAKE_SUBJECT_UNSPECIFIED",
		1: "WAKE_SUBJECT_APPROVAL",
		2: "WAKE_SUBJECT_KEY_OFFER",
	}
	WakeSubject_value = map[string]int32{
		"WAKE_SUBJECT_UNSPECIFIED": 0,
		"WAKE_SUBJECT_APPROVAL":    1,
		"WAKE_SUBJECT_KEY_OFFER":   2,
	}
)

func (x WakeSubject) Enum() *WakeSubject {
	p := new(WakeSubject)
	*p = x
	return p
}

func (x WakeSubject) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WakeSubject) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_v1_wakeup_proto_enumTypes[3].Descriptor()
}

func (WakeSubject) Type() protoreflect.EnumType {
	return &file_ladulas_v1_wakeup_proto_enumTypes[3]
}

func (x WakeSubject) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WakeSubject.Descriptor instead.
func (WakeSubject) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{3}
}

// WakeOutcome is what became of it, and every value is a thing the caller acts
// on rather than a status code to log.
type WakeOutcome int32

const (
	WakeOutcome_WAKE_OUTCOME_UNSPECIFIED WakeOutcome = 0
	// Handed to the platform.
	WakeOutcome_WAKE_OUTCOME_DELIVERED WakeOutcome = 1
	// Refused by the relay's own pacing. Not an error: the request is parked and
	// the phone will find it.
	WakeOutcome_WAKE_OUTCOME_THROTTLED WakeOutcome = 2
	// No device has ever registered under that instance id.
	WakeOutcome_WAKE_OUTCOME_UNKNOWN WakeOutcome = 3
	// The platform says the token is dead — the app was deleted, or the token was
	// reissued and this one was not. It is how a route is dropped without waiting
	// for anybody to announce anything, and is the other half of token rotation.
	WakeOutcome_WAKE_OUTCOME_UNREGISTERED WakeOutcome = 4
)

// Enum value maps for WakeOutcome.
var (
	WakeOutcome_name = map[int32]string{
		0: "WAKE_OUTCOME_UNSPECIFIED",
		1: "WAKE_OUTCOME_DELIVERED",
		2: "WAKE_OUTCOME_THROTTLED",
		3: "WAKE_OUTCOME_UNKNOWN",
		4: "WAKE_OUTCOME_UNREGISTERED",
	}
	WakeOutcome_value = map[string]int32{
		"WAKE_OUTCOME_UNSPECIFIED":  0,
		"WAKE_OUTCOME_DELIVERED":    1,
		"WAKE_OUTCOME_THROTTLED":    2,
		"WAKE_OUTCOME_UNKNOWN":      3,
		"WAKE_OUTCOME_UNREGISTERED": 4,
	}
)

func (x WakeOutcome) Enum() *WakeOutcome {
	p := new(WakeOutcome)
	*p = x
	return p
}

func (x WakeOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WakeOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_ladulas_v1_wakeup_proto_enumTypes[4].Descriptor()
}

func (WakeOutcome) Type() protoreflect.EnumType {
	return &file_ladulas_v1_wakeup_proto_enumTypes[4]
}

func (x WakeOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WakeOutcome.Descriptor instead.
func (WakeOutcome) EnumDescriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{4}
}

// WakeupRoute is where to knock, and is deliberately the whole of what a
// requester is told.
//
// The instance id is minted by the approver, is random, and means nothing
// anywhere but at that relay. It is a capability rather than a name: whoever
// holds it can cause an empty notification on that device and nothing else, so
// it travels only over the peer channel and is replaced by announcing a new one.
type WakeupRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  WakeupKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=ladulas.v1.WakeupKind" json:"kind,omitempty"`
	// The relay's base URL. Configuration on the approver and nothing on the
	// requester, which is what makes self-hosting a build of the app rather than
	// a fork of everything that talks to it (§11).
	RelayUrl      string `protobuf:"bytes,2,opt,name=relay_url,json=relayUrl,proto3" json:"relay_url,omitempty"`
	InstanceId    string `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeupRoute) Reset() {
	*x = WakeupRoute{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeupRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeupRoute) ProtoMessage() {}

func (x *WakeupRoute) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeupRoute.ProtoReflect.Descriptor instead.
func (*WakeupRoute) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{0}
}

func (x *WakeupRoute) GetKind() WakeupKind {
	if x != nil {
		return x.Kind
	}
	return WakeupKind_WAKEUP_KIND_UNSPECIFIED
}

func (x *WakeupRoute) GetRelayUrl() string {
	if x != nil {
		return x.RelayUrl
	}
	return ""
}

func (x *WakeupRoute) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type AnnounceWakeupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absent withdraws whatever the requester holds for this peer.
	Route *WakeupRoute `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	// Until when this instance expects to answer this requester without asking
	// anybody — the latest expiry among the grants it holds that cover that
	// requester (§20, M9).
	//
	// It is what the silent-push carve-out is decided from, and it is a hint in
	// the strict sense: a requester that ignores it sends the alert push it would
	// always have sent, and an approver whose grant was revoked a second ago
	// wakes quietly once more and then polls, finds a request, and asks.
	QuietUntil    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=quiet_until,json=quietUntil,proto3" json:"quiet_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceWakeupRequest) Reset() {
	*x = AnnounceWakeupRequest{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceWakeupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceWakeupRequest) ProtoMessage() {}

func (x *AnnounceWakeupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceWakeupRequest.ProtoReflect.Descriptor instead.
func (*AnnounceWakeupRequest) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{1}
}

func (x *AnnounceWakeupRequest) GetRoute() *WakeupRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *AnnounceWakeupRequest) GetQuietUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.QuietUntil
	}
	return nil
}

type AnnounceWakeupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the requester will use it. A requester that will not dial the URL —
	// cleartext, or wake-ups switched off there — says so, so that a phone can
	// report "this machine will not wake me" rather than waiting to notice that
	// nothing ever arrives.
	Accepted      bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceWakeupResponse) Reset() {
	*x = AnnounceWakeupResponse{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceWakeupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceWakeupResponse) ProtoMessage() {}

func (x *AnnounceWakeupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceWakeupResponse.ProtoReflect.Descriptor instead.
func (*AnnounceWakeupResponse) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{2}
}

func (x *AnnounceWakeupResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AnnounceWakeupResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RelayCall is what an identity key signs. The two operations share one message
// so that they share one signing path and one replay window.
type RelayCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bounds replay. The relay refuses a call that is too old or too far in the
	// future; combined with the nonce it means a captured call is worth one
	// notification within a few minutes of being captured, and nothing after.
	IssuedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Nonce      string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	InstanceId string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*RelayCall_Register
	//	*RelayCall_Wake
	Operation     isRelayCall_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayCall) Reset() {
	*x = RelayCall{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayCall) ProtoMessage() {}

func (x *RelayCall) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayCall.ProtoReflect.Descriptor instead.
func (*RelayCall) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{3}
}

func (x *RelayCall) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *RelayCall) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *RelayCall) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RelayCall) GetOperation() isRelayCall_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *RelayCall) GetRegister() *DeviceRegistration {
	if x != nil {
		if x, ok := x.Operation.(*RelayCall_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *RelayCall) GetWake() *Wake {
	if x != nil {
		if x, ok := x.Operation.(*RelayCall_Wake); ok {
			return x.Wake
		}
	}
	return nil
}

type isRelayCall_Operation interface {
	isRelayCall_Operation()
}

type RelayCall_Register struct {
	Register *DeviceRegistration `protobuf:"bytes,4,opt,name=register,proto3,oneof"`
}

type RelayCall_Wake struct {
	Wake *Wake `protobuf:"bytes,5,opt,name=wake,proto3,oneof"`
}

func (*RelayCall_Register) isRelayCall_Operation() {}

func (*RelayCall_Wake) isRelayCall_Operation() {}

type DeviceRegistration struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Platform PushPlatform           `protobuf:"varint,1,opt,name=platform,proto3,enum=ladulas.v1.PushPlatform" json:"platform,omitempty"`
	// The platform's device token. Hex for APNs, which is what the shell gets
	// from didRegisterForRemoteNotificationsWithDeviceToken.
	DeviceToken   string `protobuf:"bytes,2,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRegistration) Reset() {
	*x = DeviceRegistration{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRegistration) ProtoMessage() {}

func (x *DeviceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRegistration.ProtoReflect.Descriptor instead.
func (*DeviceRegistration) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceRegistration) GetPlatform() PushPlatform {
	if x != nil {
		return x.Platform
	}
	return PushPlatform_PUSH_PLATFORM_UNSPECIFIED
}

func (x *DeviceRegistration) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

type Wake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Style         WakeStyle              `protobuf:"varint,1,opt,name=style,proto3,enum=ladulas.v1.WakeStyle" json:"style,omitempty"`
	Subject       WakeSubject            `protobuf:"varint,2,opt,name=subject,proto3,enum=ladulas.v1.WakeSubject" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wake) Reset() {
	*x = Wake{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wake) ProtoMessage() {}

func (x *Wake) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wake.ProtoReflect.Descriptor instead.
func (*Wake) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{5}
}

func (x *Wake) GetStyle() WakeStyle {
	if x != nil {
		return x.Style
	}
	return WakeStyle_WAKE_STYLE_UNSPECIFIED
}

func (x *Wake) GetSubject() WakeSubject {
	if x != nil {
		return x.Subject
	}
	return WakeSubject_WAKE_SUBJECT_UNSPECIFIED
}

// SignedRelayCall carries the exact serialized call the signature covers, for
// the reason SignedApproval does: protobuf serialization is not canonical, so
// re-marshalling to check a signature is a way to fail on bytes nobody changed.
type SignedRelayCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Call  []byte                 `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	// The caller's identity key in SSH wire format.
	PublicKey          []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	SignatureAlgorithm string `protobuf:"bytes,3,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	Signature          []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignedRelayCall) Reset() {
	*x = SignedRelayCall{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedRelayCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedRelayCall) ProtoMessage() {}

func (x *SignedRelayCall) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedRelayCall.ProtoReflect.Descriptor instead.
func (*SignedRelayCall) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{6}
}

func (x *SignedRelayCall) GetCall() []byte {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *SignedRelayCall) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedRelayCall) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *SignedRelayCall) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        *SignedRelayCall       `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRequest) GetSigned() *SignedRelayCall {
	if x != nil {
		return x.Signed
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{8}
}

type WakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        *SignedRelayCall       `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeRequest) Reset() {
	*x = WakeRequest{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeRequest) ProtoMessage() {}

func (x *WakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeRequest.ProtoReflect.Descriptor instead.
func (*WakeRequest) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{9}
}

func (x *WakeRequest) GetSigned() *SignedRelayCall {
	if x != nil {
		return x.Signed
	}
	return nil
}

type WakeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Outcome WakeOutcome            `protobuf:"varint,1,opt,name=outcome,proto3,enum=ladulas.v1.WakeOutcome" json:"outcome,omitempty"`
	// How long to wait before trying this instance again, when throttled.
	RetryAfter    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeResponse) Reset() {
	*x = WakeResponse{}
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeResponse) ProtoMessage() {}

func (x *WakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladulas_v1_wakeup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeResponse.ProtoReflect.Descriptor instead.
func (*WakeResponse) Descriptor() ([]byte, []int) {
	return file_ladulas_v1_wakeup_proto_rawDescGZIP(), []int{10}
}

func (x *WakeResponse) GetOutcome() WakeOutcome {
	if x != nil {
		return x.Outcome
	}
	return WakeOutcome_WAKE_OUTCOME_UNSPECIFIED
}

func (x *WakeResponse) GetRetryAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

var File_ladulas_v1_wakeup_proto protoreflect.FileDescriptor

const file_ladulas_v1_wakeup_proto_rawDesc = "" +
	"\n" +
	"\x17ladulas/v1/wakeup.proto\x12\n" +
	"ladulas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\vWakeupRoute\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.ladulas.v1.WakeupKindR\x04kind\x12\x1b\n" +
	"\trelay_url\x18\x02 \x01(\tR\brelayUrl\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"\x83\x01\n" +
	"\x15AnnounceWakeupRequest\x12-\n" +
	"\x05route\x18\x01 \x01(\v2\x17.ladulas.v1.WakeupRouteR\x05route\x12;\n" +
	"\vquiet_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"quietUntil\"L\n" +
	"\x16AnnounceWakeupResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xee\x01\n" +
	"\tRelayCall\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12<\n" +
	"\bregister\x18\x04 \x01(\v2\x1e.ladulas.v1.DeviceRegistrationH\x00R\bregister\x12&\n" +
	"\x04wake\x18\x05 \x01(\v2\x10.ladulas.v1.WakeH\x00R\x04wakeB\v\n" +
	"\toperation\"m\n" +
	"\x12DeviceRegistration\x124\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x18.ladulas.v1.PushPlatformR\bplatform\x12!\n" +
	"\fdevice_token\x18\x02 \x01(\tR\vdeviceToken\"f\n" +
	"\x04Wake\x12+\n" +
	"\x05style\x18\x01 \x01(\x0e2\x15.ladulas.v1.WakeStyleR\x05style\x121\n" +
	"\asubject\x18\x02 \x01(\x0e2\x17.ladulas.v1.WakeSubjectR\asubject\"\x93\x01\n" +
	"\x0fSignedRelayCall\x12\x12\n" +
	"\x04call\x18\x01 \x01(\fR\x04call\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12/\n" +
	"\x13signature_algorithm\x18\x03 \x01(\tR\x12signatureAlgorithm\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"F\n" +
	"\x0fRegisterRequest\x123\n" +
	"\x06signed\x18\x01 \x01(\v2\x1b.ladulas.v1.SignedRelayCallR\x06signed\"\x12\n" +
	"\x10RegisterResponse\"B\n" +
	"\vWakeRequest\x123\n" +
	"\x06signed\x18\x01 \x01(\v2\x1b.ladulas.v1.SignedRelayCallR\x06signed\"~\n" +
	"\fWakeResponse\x121\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x17.ladulas.v1.WakeOutcomeR\aoutcome\x12;\n" +
	"\vretry_after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"retryAfter*@\n" +
	"\n" +
	"WakeupKind\x12\x1b\n" +
	"\x17WAKEUP_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WAKEUP_KIND_RELAY\x10\x01*\\\n" +
	"\fPushPlatform\x12\x1d\n" +
	"\x19PUSH_PLATFORM_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PUSH_PLATFORM_APNS\x10\x01\x12\x15\n" +
	"\x11PUSH_PLATFORM_FCM\x10\x02*T\n" +
	"\tWakeStyle\x12\x1a\n" +
	"\x16WAKE_STYLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10WAKE_STYLE_ALERT\x10\x01\x12\x15\n" +
	"\x11WAKE_STYLE_SILENT\x10\x02*b\n" +
	"\vWakeSubject\x12\x1c\n" +
	"\x18WAKE_SUBJECT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WAKE_SUBJECT_APPROVAL\x10\x01\x12\x1a\n" +
	"\x16WAKE_SUBJECT_KEY_OFFER\x10\x02*\x9c\x01\n" +
	"\vWakeOutcome\x12\x1c\n" +
	"\x18WAKE_OUTCOME_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WAKE_OUTCOME_DELIVERED\x10\x01\x12\x1a\n" +
	"\x16WAKE_OUTCOME_THROTTLED\x10\x02\x12\x18\n" +
	"\x14WAKE_OUTCOME_UNKNOWN\x10\x03\x12\x1d\n" +
	"\x19WAKE_OUTCOME_UNREGISTERED\x10\x042h\n" +
	"\rWakeupService\x12W\n" +
	"\x0eAnnounceWakeup\x12!.ladulas.v1.AnnounceWakeupRequest\x1a\".ladulas.v1.AnnounceWakeupResponse2\x90\x01\n" +
	"\fRelayService\x12E\n" +
	"\bRegister\x12\x1b.ladulas.v1.RegisterRequest\x1a\x1c.ladulas.v1.RegisterResponse\x129\n" +
	"\x04Wake\x12\x17.ladulas.v1.WakeRequest\x1a\x18.ladulas.v1.WakeResponseBDZBgithub.com/hugowetterberg/ladulas/pkg/protocol/ladulasv1;ladulasv1b\x06proto3"

var (
	file_ladulas_v1_wakeup_proto_rawDescOnce sync.Once
	file_ladulas_v1_wakeup_proto_rawDescData []byte
)

func file_ladulas_v1_wakeup_proto_rawDescGZIP() []byte {
	file_ladulas_v1_wakeup_proto_rawDescOnce.Do(func() {
		file_ladulas_v1_wakeup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ladulas_v1_wakeup_proto_rawDesc), len(file_ladulas_v1_wakeup_proto_rawDesc)))
	})
	return file_ladulas_v1_wakeup_proto_rawDescData
}

var file_ladulas_v1_wakeup_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_ladulas_v1_wakeup_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ladulas_v1_wakeup_proto_goTypes = []any{
	(WakeupKind)(0),                // 0: ladulas.v1.WakeupKind
	(PushPlatform)(0),              // 1: ladulas.v1.PushPlatform
	(WakeStyle)(0),                 // 2: ladulas.v1.WakeStyle
	(WakeSubject)(0),               // 3: ladulas.v1.WakeSubject
	(WakeOutcome)(0),               // 4: ladulas.v1.WakeOutcome
	(*WakeupRoute)(nil),            // 5: ladulas.v1.WakeupRoute
	(*AnnounceWakeupRequest)(nil),  // 6: ladulas.v1.AnnounceWakeupRequest
	(*AnnounceWakeupResponse)(nil), // 7: ladulas.v1.AnnounceWakeupResponse
	(*RelayCall)(nil),              // 8: ladulas.v1.RelayCall
	(*DeviceRegistration)(nil),     // 9: ladulas.v1.DeviceRegistration
	(*Wake)(nil),                   // 10: ladulas.v1.Wake
	(*SignedRelayCall)(nil),        // 11: ladulas.v1.SignedRelayCall
	(*RegisterRequest)(nil),        // 12: ladulas.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 13: ladulas.v1.RegisterResponse
	(*WakeRequest)(nil),            // 14: ladulas.v1.WakeRequest
	(*WakeResponse)(nil),           // 15: ladulas.v1.WakeResponse
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
}
var file_ladulas_v1_wakeup_proto_depIdxs = []int32{
	0,  // 0: ladulas.v1.WakeupRoute.kind:type_name -> ladulas.v1.WakeupKind
	5,  // 1: ladulas.v1.AnnounceWakeupRequest.route:type_name -> ladulas.v1.WakeupRoute
	16, // 2: ladulas.v1.AnnounceWakeupRequest.quiet_until:type_name -> google.protobuf.Timestamp
	16, // 3: ladulas.v1.RelayCall.issued_at:type_name -> google.protobuf.Timestamp
	9,  // 4: ladulas.v1.RelayCall.register:type_name -> ladulas.v1.DeviceRegistration
	10, // 5: ladulas.v1.RelayCall.wake:type_name -> ladulas.v1.Wake
	1,  // 6: ladulas.v1.DeviceRegistration.platform:type_name -> ladulas.v1.PushPlatform
	2,  // 7: ladulas.v1.Wake.style:type_name -> ladulas.v1.WakeStyle
	3,  // 8: ladulas.v1.Wake.subject:type_name -> ladulas.v1.WakeSubject
	11, // 9: ladulas.v1.RegisterRequest.signed:type_name -> ladulas.v1.SignedRelayCall
	11, // 10: ladulas.v1.WakeRequest.signed:type_name -> ladulas.v1.SignedRelayCall
	4,  // 11: ladulas.v1.WakeResponse.outcome:type_name -> ladulas.v1.WakeOutcome
	16, // 12: ladulas.v1.WakeResponse.retry_after:type_name -> google.protobuf.Timestamp
	6,  // 13: ladulas.v1.WakeupService.AnnounceWakeup:input_type -> ladulas.v1.AnnounceWakeupRequest
	12, // 14: ladulas.v1.RelayService.Register:input_type -> ladulas.v1.RegisterRequest
	14, // 15: ladulas.v1.RelayService.Wake:input_type -> ladulas.v1.WakeRequest
	7,  // 16: ladulas.v1.WakeupService.AnnounceWakeup:output_type -> ladulas.v1.AnnounceWakeupResponse
	13, // 17: ladulas.v1.RelayService.Register:output_type -> ladulas.v1.RegisterResponse
	15, // 18: ladulas.v1.RelayService.Wake:output_type -> ladulas.v1.WakeResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ladulas_v1_wakeup_proto_init() }
func file_ladulas_v1_wakeup_proto_init() {
	if File_ladulas_v1_wakeup_proto != nil {
		return
	}
	file_ladulas_v1_wakeup_proto_msgTypes[3].OneofWrappers = []any{
		(*RelayCall_Register)(nil),
		(*RelayCall_Wake)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ladulas_v1_wakeup_proto_rawDesc), len(file_ladulas_v1_wakeup_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ladulas_v1_wakeup_proto_goTypes,
		DependencyIndexes: file_ladulas_v1_wakeup_proto_depIdxs,
		EnumInfos:         file_ladulas_v1_wakeup_proto_enumTypes,
		MessageInfos:      file_ladulas_v1_wakeup_proto_msgTypes,
	}.Build()
	File_ladulas_v1_wakeup_proto = out.File
	file_ladulas_v1_wakeup_proto_goTypes = nil
	file_ladulas_v1_wakeup_proto_depIdxs = nil
}
